/**
 * @fileoverview Mock doer data for development and demonstration.
 * @module lib/mock-data/doers
 */

import type { Doer, DoerReview, DoerProject } from "@/components/doers/types"

/** Mock doers for development */
export const MOCK_DOERS: Doer[] = [
  {
    id: "doer-1",
    full_name: "Amit Sharma",
    email: "amit.sharma@example.com",
    phone: "+91 98765 43210",
    qualification: "M.A. Economics",
    years_of_experience: 5,
    skills: ["Economic Analysis", "Data Interpretation", "Research Writing", "Statistics", "Econometrics"],
    subjects: ["Economics", "Finance", "Statistics"],
    bio: "Passionate economics researcher with expertise in macroeconomic policy analysis.",
    rating: 4.8,
    total_reviews: 45,
    total_projects: 78,
    completed_projects: 75,
    active_projects: 3,
    success_rate: 96,
    average_response_time: "1.5h",
    joined_at: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(),
    is_available: true,
    is_verified: true,
    is_blacklisted: false,
  },
  {
    id: "doer-2",
    full_name: "Priya Patel",
    email: "priya.patel@example.com",
    qualification: "MBA Marketing",
    years_of_experience: 4,
    skills: ["Marketing Strategy", "Brand Management", "Consumer Behavior", "Digital Marketing"],
    subjects: ["Marketing", "Business Studies"],
    rating: 4.6,
    total_reviews: 32,
    total_projects: 52,
    completed_projects: 48,
    active_projects: 2,
    success_rate: 92,
    average_response_time: "2h",
    joined_at: new Date(Date.now() - 280 * 24 * 60 * 60 * 1000).toISOString(),
    is_available: true,
    is_verified: true,
  },
  {
    id: "doer-3",
    full_name: "Rahul Verma",
    email: "rahul.verma@example.com",
    qualification: "Ph.D. Finance",
    years_of_experience: 8,
    skills: ["Financial Modeling", "Investment Analysis", "Risk Management", "Portfolio Management"],
    subjects: ["Finance", "Accounting", "Economics"],
    rating: 4.9,
    total_reviews: 89,
    total_projects: 124,
    completed_projects: 120,
    active_projects: 4,
    success_rate: 97,
    average_response_time: "1h",
    joined_at: new Date(Date.now() - 730 * 24 * 60 * 60 * 1000).toISOString(),
    is_available: false,
    is_verified: true,
  },
  {
    id: "doer-4",
    full_name: "Sneha Gupta",
    email: "sneha.gupta@example.com",
    qualification: "M.Sc. Computer Science",
    years_of_experience: 3,
    skills: ["Python", "Machine Learning", "Data Science", "Deep Learning"],
    subjects: ["Computer Science", "Data Science"],
    rating: 4.5,
    total_reviews: 28,
    total_projects: 35,
    completed_projects: 32,
    active_projects: 2,
    success_rate: 91,
    average_response_time: "3h",
    joined_at: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    is_available: true,
    is_verified: true,
  },
  {
    id: "doer-5",
    full_name: "Vikram Singh",
    email: "vikram.singh@example.com",
    qualification: "B.Tech Mechanical",
    years_of_experience: 2,
    skills: ["CAD Design", "Thermodynamics", "Fluid Mechanics"],
    subjects: ["Mechanical Engineering"],
    rating: 3.8,
    total_reviews: 12,
    total_projects: 18,
    completed_projects: 14,
    active_projects: 1,
    success_rate: 78,
    joined_at: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    is_available: true,
    is_verified: false,
    is_blacklisted: true,
    blacklist_reason: "Missed multiple deadlines and poor communication",
  },
]

/** Mock doer reviews */
export const MOCK_DOER_REVIEWS: DoerReview[] = [
  {
    id: "review-1",
    doer_id: "doer-1",
    project_id: "proj-1",
    project_number: "AX-00115",
    rating: 5,
    comment: "Excellent work on my economics assignment. Delivered ahead of time.",
    reviewer_name: "Anonymous",
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "review-2",
    doer_id: "doer-1",
    project_id: "proj-2",
    project_number: "AX-00098",
    rating: 4,
    comment: "Good research paper. Minor formatting issues but overall satisfied.",
    reviewer_name: "Anonymous",
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

/** Mock doer projects */
export const MOCK_DOER_PROJECTS: DoerProject[] = [
  {
    id: "proj-1",
    project_number: "AX-00115",
    title: "Macroeconomic Policy Analysis",
    status: "completed",
    deadline: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    amount: 1625,
    completed_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "proj-2",
    project_number: "AX-00098",
    title: "Statistical Analysis of Market Trends",
    status: "completed",
    deadline: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    amount: 1300,
    completed_at: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

/** Available subjects for filtering */
export const SUBJECT_OPTIONS = [
  "All Subjects",
  "Economics",
  "Finance",
  "Marketing",
  "Computer Science",
  "Engineering",
  "Statistics",
]
