/**
 * @fileoverview Mock project data for development and UI testing.
 * @module lib/mock-data/projects
 */

import type { ProjectRequest } from "@/components/dashboard/request-card"
import type { ActiveProject } from "@/components/projects/types"

/** Mock project requests for dashboard testing */
export const MOCK_PROJECT_REQUESTS: ProjectRequest[] = [
  {
    id: "req-1",
    project_number: "AX-00245",
    title: "Macroeconomic Analysis of Indian Banking Sector Post-Demonetization",
    subject: "Economics",
    service_type: "new_project",
    user_name: "Jasvin Taneja",
    deadline: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(), // 8 hours from now
    word_count: 3500,
    page_count: 12,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    priority: "urgent",
    attachments_count: 3,
  },
  {
    id: "req-2",
    project_number: "AX-00246",
    title: "Digital Marketing Strategy for E-commerce Startup",
    subject: "Marketing",
    service_type: "new_project",
    user_name: "Arjun Mehta",
    deadline: new Date(Date.now() + 36 * 60 * 60 * 1000).toISOString(), // 36 hours
    word_count: 2500,
    page_count: 9,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    priority: "normal",
    attachments_count: 2,
  },
  {
    id: "req-3",
    project_number: "AX-00247",
    title: "Statistical Analysis of Climate Change Impact on Agriculture",
    subject: "Statistics",
    service_type: "new_project",
    user_name: "Neha Kapoor",
    deadline: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(), // 4 hours - critical
    word_count: 4200,
    page_count: 15,
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    priority: "critical",
    attachments_count: 5,
  },
  {
    id: "req-4",
    project_number: "AX-00248",
    title: "Corporate Finance: Valuation of Tech Startups",
    subject: "Finance",
    service_type: "new_project",
    user_name: "Vikash Yadav",
    deadline: new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString(), // 3 days
    word_count: 3000,
    page_count: 11,
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    priority: "normal",
    attachments_count: 1,
  },
  {
    id: "req-5",
    project_number: "AX-00249",
    title: "Machine Learning Applications in Healthcare Diagnostics",
    subject: "Computer Science",
    service_type: "new_project",
    user_name: "Shreya Sharma",
    deadline: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(), // 2 days
    word_count: 5000,
    page_count: 18,
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    priority: "normal",
    attachments_count: 7,
  },
  {
    id: "req-6",
    project_number: "AX-00250",
    title: "Business Ethics Case Study: Corporate Social Responsibility",
    subject: "Business Studies",
    service_type: "new_project",
    user_name: "Rahul Agarwal",
    deadline: new Date(Date.now() + 20 * 60 * 60 * 1000).toISOString(), // 20 hours - urgent
    word_count: 2800,
    page_count: 10,
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    priority: "urgent",
    attachments_count: 2,
  },
  {
    id: "req-7",
    project_number: "AX-00251",
    title: "Plagiarism Check for Research Paper on Quantum Computing",
    subject: "Physics",
    service_type: "plagiarism_check",
    user_name: "Pooja Reddy",
    deadline: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(), // 12 hours
    word_count: 6000,
    page_count: 22,
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    priority: "normal",
    attachments_count: 1,
  },
  {
    id: "req-8",
    project_number: "AX-00252",
    title: "AI Detection Check for MBA Assignment",
    subject: "Management",
    service_type: "ai_detection",
    user_name: "Jasvin Taneja",
    deadline: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(), // 6 hours
    word_count: 1500,
    page_count: 5,
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    priority: "normal",
    attachments_count: 1,
  },
  {
    id: "req-9",
    project_number: "AX-00253",
    title: "Proofreading: Dissertation on Behavioral Economics",
    subject: "Economics",
    service_type: "proofreading",
    user_name: "Arjun Mehta",
    deadline: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(), // 1 day
    word_count: 12000,
    page_count: 45,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    priority: "normal",
    attachments_count: 2,
  },
  {
    id: "req-10",
    project_number: "AX-00254",
    title: "Expert Opinion: Investment Portfolio Analysis",
    subject: "Finance",
    service_type: "expert_opinion",
    user_name: "Neha Kapoor",
    deadline: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(), // 3 hours - critical
    word_count: 1000,
    page_count: 4,
    created_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    priority: "critical",
    attachments_count: 4,
  },
]

/** Mock active/ongoing projects */
export const MOCK_ACTIVE_PROJECTS: ActiveProject[] = [
  {
    id: "proj-active-1",
    project_number: "AX-00240",
    title: "Financial Accounting Comprehensive Project",
    subject: "Accounting",
    service_type: "Assignment Writing",
    status: "in_progress",
    user_name: "Vikash Yadav",
    user_id: "student-004",
    deadline: new Date(Date.now() + 28 * 60 * 60 * 1000).toISOString(),
    word_count: 4000,
    page_count: 14,
    quoted_amount: 4200,
    doer_payout: 3150,
    supervisor_commission: 485.50,
    doer_name: "Amit Sharma",
    doer_id: "doer-1",
    assigned_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    has_unread_messages: true,
    revision_count: 0,
  },
  {
    id: "proj-active-2",
    project_number: "AX-00238",
    title: "Marketing Research: Consumer Behavior Analysis",
    subject: "Marketing",
    service_type: "Research Paper",
    status: "in_progress",
    user_name: "Arjun Mehta",
    user_id: "student-001",
    deadline: new Date(Date.now() + 15 * 60 * 60 * 1000).toISOString(),
    word_count: 3500,
    page_count: 12,
    quoted_amount: 3800,
    doer_payout: 2850,
    supervisor_commission: 425.75,
    doer_name: "Priya Patel",
    doer_id: "doer-2",
    assigned_at: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
    has_unread_messages: false,
    revision_count: 1,
  },
  {
    id: "proj-active-3",
    project_number: "AX-00235",
    title: "Data Science Project: Predictive Analytics",
    subject: "Computer Science",
    service_type: "Programming Assignment",
    status: "in_progress",
    user_name: "Neha Kapoor",
    user_id: "student-002",
    deadline: new Date(Date.now() + 60 * 60 * 60 * 1000).toISOString(),
    word_count: 2500,
    page_count: 9,
    quoted_amount: 5500,
    doer_payout: 4125,
    supervisor_commission: 625.00,
    doer_name: "Sneha Gupta",
    doer_id: "doer-4",
    assigned_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    has_unread_messages: true,
    revision_count: 0,
  },
  {
    id: "proj-active-4",
    project_number: "AX-00230",
    title: "Operations Management Case Study",
    subject: "Business Studies",
    service_type: "Case Study",
    status: "submitted_for_qc",
    user_name: "Shreya Sharma",
    user_id: "student-003",
    deadline: new Date(Date.now() + 10 * 60 * 60 * 1000).toISOString(),
    word_count: 3200,
    page_count: 11,
    quoted_amount: 3400,
    doer_payout: 2550,
    supervisor_commission: 390.00,
    doer_name: "Rahul Verma",
    doer_id: "doer-3",
    assigned_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 120 * 60 * 60 * 1000).toISOString(),
    has_unread_messages: false,
    revision_count: 0,
  },
  {
    id: "proj-active-5",
    project_number: "AX-00228",
    title: "International Business Strategy Analysis",
    subject: "International Business",
    service_type: "Strategic Analysis",
    status: "in_progress",
    user_name: "Pooja Reddy",
    user_id: "student-005",
    deadline: new Date(Date.now() + 40 * 60 * 60 * 1000).toISOString(),
    word_count: 4500,
    page_count: 16,
    quoted_amount: 4800,
    doer_payout: 3600,
    supervisor_commission: 545.25,
    doer_name: "Amit Sharma",
    doer_id: "doer-1",
    assigned_at: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 144 * 60 * 60 * 1000).toISOString(),
    has_unread_messages: true,
    revision_count: 2,
  },
]

/** Mock projects ready to assign to doers */
export const MOCK_READY_TO_ASSIGN: any[] = [
  {
    id: "ready-1",
    project_number: "AX-00255",
    title: "Organizational Behavior Study: Leadership Styles",
    subject: "Management",
    service_type: "new_project",
    user_quote: 3200,
    doer_payout: 2400,
    supervisor_commission: 480,
    deadline: new Date(Date.now() + 96 * 60 * 60 * 1000).toISOString(), // 4 days
    word_count: 3800,
    page_count: 13,
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ready-2",
    project_number: "AX-00256",
    title: "Supply Chain Management Optimization",
    subject: "Operations Management",
    service_type: "new_project",
    user_quote: 2800,
    doer_payout: 2100,
    supervisor_commission: 420,
    deadline: new Date(Date.now() + 84 * 60 * 60 * 1000).toISOString(),
    word_count: 3000,
    page_count: 10,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ready-3",
    project_number: "AX-00257",
    title: "Econometrics Analysis of Stock Market Volatility",
    subject: "Economics",
    service_type: "new_project",
    user_quote: 4500,
    doer_payout: 3375,
    supervisor_commission: 675,
    deadline: new Date(Date.now() + 120 * 60 * 60 * 1000).toISOString(), // 5 days
    word_count: 5500,
    page_count: 20,
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
]

/** Mock completed projects */
export const MOCK_COMPLETED_PROJECTS: any[] = [
  {
    id: "comp-1",
    project_number: "AX-00220",
    title: "Financial Statement Analysis",
    subject: "Finance",
    status: "completed",
    deadline: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    supervisor_commission: 425.00,
    doer_name: "Rahul Verma",
    rating: 5,
  },
  {
    id: "comp-2",
    project_number: "AX-00215",
    title: "Marketing Mix Strategy for FMCG Brand",
    subject: "Marketing",
    status: "completed",
    deadline: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    supervisor_commission: 385.50,
    doer_name: "Priya Patel",
    rating: 4,
  },
  {
    id: "comp-3",
    project_number: "AX-00210",
    title: "Database Management System Design",
    subject: "Computer Science",
    status: "completed",
    deadline: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    completed_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    supervisor_commission: 550.00,
    doer_name: "Sneha Gupta",
    rating: 5,
  },
]

/** Helper to get projects by status */
export function getMockProjectsByStatus() {
  return {
    needsQuote: MOCK_PROJECT_REQUESTS,
    readyToAssign: MOCK_READY_TO_ASSIGN,
    inProgress: MOCK_ACTIVE_PROJECTS.filter(p => p.status === "in_progress"),
    needsQC: MOCK_ACTIVE_PROJECTS.filter(p => p.status === "submitted_for_qc"),
    completed: MOCK_COMPLETED_PROJECTS,
  }
}

/** Helper to get mock supervisor stats */
export function getMockSupervisorStats() {
  return {
    activeProjects: MOCK_ACTIVE_PROJECTS.length,
    completedProjects: MOCK_COMPLETED_PROJECTS.length,
    totalEarnings: 12850.75,
    thisMonthEarnings: 4250.25,
    averageRating: 4.7,
    totalProjects: MOCK_PROJECT_REQUESTS.length + MOCK_ACTIVE_PROJECTS.length + MOCK_COMPLETED_PROJECTS.length,
  }
}
