// Copyright 2024 Doer App. All rights reserved.
// Use of this source code is governed by a BSD-style license.

/// Activation models for the Doer application.
///
/// This file contains models related to the doer activation process,
/// which is a 3-step onboarding flow that doers must complete before
/// they can accept and work on projects.
///
/// ## Activation Flow Overview
///
/// ```
/// Step 1: Training
///    │
///    ├── Watch training videos/read materials
///    ├── Complete all required modules
///    └── Progress tracked in training_progress table
///    │
///    ▼
/// Step 2: Quiz
///    │
///    ├── Answer interview questions
///    ├── Score >= 80% required to pass
///    └── Multiple attempts allowed
///    │
///    ▼
/// Step 3: Bank Details
///    │
///    ├── Submit bank account information
///    ├── IFSC code validation
///    └── Optional UPI ID
///    │
///    ▼
/// ACTIVATED - Can now accept projects
/// ```
///
/// ## Models in this file
///
/// - [ActivationStatus] - Database model tracking activation progress
/// - [ActivationStep] - Enum defining the 3 activation steps
/// - [ActivationState] - Full state including modules, progress, and errors
library activation_model;

import 'bank_details_model.dart';
import 'quiz_model.dart';
import 'training_model.dart';

/// Activation status model matching the `doer_activation` table.
///
/// This model tracks a doer's progress through the 3-step activation process:
/// training, quiz, and bank details. It maintains timestamps and flags for
/// each completed step.
///
/// ## JSON Structure
///
/// ```json
/// {
///   "id": "activation-uuid",
///   "doer_id": "doer-uuid",
///   "training_completed": true,
///   "training_completed_at": "2024-01-10T15:30:00Z",
///   "quiz_passed": true,
///   "quiz_passed_at": "2024-01-12T10:00:00Z",
///   "quiz_attempt_id": "attempt-uuid",
///   "total_quiz_attempts": 2,
///   "bank_details_added": true,
///   "bank_details_added_at": "2024-01-15T09:00:00Z",
///   "is_fully_activated": true,
///   "activated_at": "2024-01-15T09:00:00Z",
///   "created_at": "2024-01-01T00:00:00Z",
///   "updated_at": "2024-01-15T09:00:00Z"
/// }
/// ```
///
/// ## Usage
///
/// ```dart
/// // Check activation progress
/// final status = ActivationStatus.fromJson(data);
/// print('Completed ${status.completedSteps}/${status.totalSteps} steps');
/// print('Progress: ${status.completionPercentage}%');
///
/// // Determine current step
/// if (!status.trainingCompleted) {
///   showTrainingScreen();
/// } else if (!status.quizPassed) {
///   showQuizScreen();
/// } else if (!status.bankDetailsAdded) {
///   showBankDetailsScreen();
/// }
/// ```
///
/// ## See Also
///
/// - [ActivationState] for the full state including modules and progress
/// - [TrainingModule] and [TrainingProgress] for training step details
/// - [QuizQuestion] and [QuizAttempt] for quiz step details
/// - [BankDetails] for bank details step
class ActivationStatus {
  /// Unique identifier for this activation record.
  ///
  /// UUID generated by the database.
  final String id;

  /// Reference to the doer whose activation this tracks.
  ///
  /// Foreign key to `doers.id`.
  final String doerId;

  /// Whether all required training modules have been completed.
  ///
  /// Set to `true` when the doer has finished watching/reading all
  /// required training materials.
  final bool trainingCompleted;

  /// Timestamp when training was completed.
  ///
  /// `null` if training is not yet complete.
  final DateTime? trainingCompletedAt;

  /// Whether the doer has passed the activation quiz.
  ///
  /// Requires a score of 80% or higher.
  final bool quizPassed;

  /// Timestamp when the quiz was passed.
  ///
  /// `null` if quiz has not been passed yet.
  final DateTime? quizPassedAt;

  /// Reference to the successful quiz attempt.
  ///
  /// Foreign key to `quiz_attempts.id`. `null` if not passed.
  final String? quizAttemptId;

  /// Total number of quiz attempts made by this doer.
  ///
  /// Tracked for analytics and potential rate limiting.
  final int totalQuizAttempts;

  /// Whether bank details have been submitted.
  ///
  /// Does not indicate verification status.
  final bool bankDetailsAdded;

  /// Timestamp when bank details were added.
  ///
  /// `null` if bank details have not been submitted.
  final DateTime? bankDetailsAddedAt;

  /// Whether all activation steps are complete.
  ///
  /// `true` when [trainingCompleted], [quizPassed], and [bankDetailsAdded]
  /// are all `true`.
  final bool isFullyActivated;

  /// Timestamp when full activation was achieved.
  ///
  /// Set when [isFullyActivated] becomes `true`.
  final DateTime? activatedAt;

  /// Timestamp when this activation record was created.
  ///
  /// Typically created when the doer profile is created.
  final DateTime createdAt;

  /// Timestamp when this record was last updated.
  ///
  /// Updated whenever any activation step is completed.
  final DateTime? updatedAt;

  /// Creates a new [ActivationStatus] with the specified values.
  ///
  /// Required parameters:
  /// - [id]: Unique activation record identifier
  /// - [doerId]: Reference to the doer
  /// - [createdAt]: Creation timestamp
  const ActivationStatus({
    required this.id,
    required this.doerId,
    this.trainingCompleted = false,
    this.trainingCompletedAt,
    this.quizPassed = false,
    this.quizPassedAt,
    this.quizAttemptId,
    this.totalQuizAttempts = 0,
    this.bankDetailsAdded = false,
    this.bankDetailsAddedAt,
    this.isFullyActivated = false,
    this.activatedAt,
    required this.createdAt,
    this.updatedAt,
  });

  /// Creates an [ActivationStatus] from a JSON map (database response).
  ///
  /// @param json The JSON map from the database response.
  /// @returns A new [ActivationStatus] instance.
  factory ActivationStatus.fromJson(Map<String, dynamic> json) {
    return ActivationStatus(
      id: json['id'] as String,
      doerId: json['doer_id'] as String,
      trainingCompleted: json['training_completed'] as bool? ?? false,
      trainingCompletedAt: json['training_completed_at'] != null
          ? DateTime.parse(json['training_completed_at'] as String)
          : null,
      quizPassed: json['quiz_passed'] as bool? ?? false,
      quizPassedAt: json['quiz_passed_at'] != null
          ? DateTime.parse(json['quiz_passed_at'] as String)
          : null,
      quizAttemptId: json['quiz_attempt_id'] as String?,
      totalQuizAttempts: json['total_quiz_attempts'] as int? ?? 0,
      bankDetailsAdded: json['bank_details_added'] as bool? ?? false,
      bankDetailsAddedAt: json['bank_details_added_at'] != null
          ? DateTime.parse(json['bank_details_added_at'] as String)
          : null,
      isFullyActivated: json['is_fully_activated'] as bool? ?? false,
      activatedAt: json['activated_at'] != null
          ? DateTime.parse(json['activated_at'] as String)
          : null,
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: json['updated_at'] != null
          ? DateTime.parse(json['updated_at'] as String)
          : null,
    );
  }

  /// Converts this [ActivationStatus] to a JSON map.
  ///
  /// @returns A map of column names to values.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'doer_id': doerId,
      'training_completed': trainingCompleted,
      'training_completed_at': trainingCompletedAt?.toIso8601String(),
      'quiz_passed': quizPassed,
      'quiz_passed_at': quizPassedAt?.toIso8601String(),
      'quiz_attempt_id': quizAttemptId,
      'total_quiz_attempts': totalQuizAttempts,
      'bank_details_added': bankDetailsAdded,
      'bank_details_added_at': bankDetailsAddedAt?.toIso8601String(),
      'is_fully_activated': isFullyActivated,
      'activated_at': activatedAt?.toIso8601String(),
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt?.toIso8601String(),
    };
  }

  /// Creates a copy of this [ActivationStatus] with updated fields.
  ///
  /// @returns A new [ActivationStatus] instance with the specified changes.
  ActivationStatus copyWith({
    String? id,
    String? doerId,
    bool? trainingCompleted,
    DateTime? trainingCompletedAt,
    bool? quizPassed,
    DateTime? quizPassedAt,
    String? quizAttemptId,
    int? totalQuizAttempts,
    bool? bankDetailsAdded,
    DateTime? bankDetailsAddedAt,
    bool? isFullyActivated,
    DateTime? activatedAt,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return ActivationStatus(
      id: id ?? this.id,
      doerId: doerId ?? this.doerId,
      trainingCompleted: trainingCompleted ?? this.trainingCompleted,
      trainingCompletedAt: trainingCompletedAt ?? this.trainingCompletedAt,
      quizPassed: quizPassed ?? this.quizPassed,
      quizPassedAt: quizPassedAt ?? this.quizPassedAt,
      quizAttemptId: quizAttemptId ?? this.quizAttemptId,
      totalQuizAttempts: totalQuizAttempts ?? this.totalQuizAttempts,
      bankDetailsAdded: bankDetailsAdded ?? this.bankDetailsAdded,
      bankDetailsAddedAt: bankDetailsAddedAt ?? this.bankDetailsAddedAt,
      isFullyActivated: isFullyActivated ?? this.isFullyActivated,
      activatedAt: activatedAt ?? this.activatedAt,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  /// Gets the number of completed activation steps.
  ///
  /// Counts how many of the 3 steps (training, quiz, bank details)
  /// have been completed.
  ///
  /// @returns An integer from 0 to 3.
  int get completedSteps {
    int count = 0;
    if (trainingCompleted) count++;
    if (quizPassed) count++;
    if (bankDetailsAdded) count++;
    return count;
  }

  /// Gets the total number of activation steps.
  ///
  /// Currently fixed at 3 (training, quiz, bank details).
  ///
  /// @returns Always returns 3.
  int get totalSteps => 3;

  /// Gets the completion percentage as a value from 0 to 100.
  ///
  /// Calculated as: (completedSteps / totalSteps) * 100
  ///
  /// @returns A double from 0.0 to 100.0.
  ///
  /// ## Example
  ///
  /// ```dart
  /// final progress = status.completionPercentage;
  /// LinearProgressIndicator(value: progress / 100);
  /// ```
  double get completionPercentage => (completedSteps / totalSteps) * 100;

  /// Gets the current step number (1-indexed).
  ///
  /// Returns which step the doer should be working on:
  /// - 1: Training (if not completed)
  /// - 2: Quiz (if training done but quiz not passed)
  /// - 3: Bank Details (if quiz passed but bank not added)
  ///
  /// @returns An integer from 1 to 3.
  int get currentStep {
    if (!trainingCompleted) return 1;
    if (!quizPassed) return 2;
    if (!bankDetailsAdded) return 3;
    return 3;
  }
}

// =============================================================================
// Activation Step Enum
// =============================================================================

/// Enumeration of the 3 activation steps.
///
/// Each step has an associated number, title, and description that can be
/// used in the UI to display step information.
///
/// ## Usage
///
/// ```dart
/// // Display step information
/// for (final step in ActivationStep.values) {
///   print('Step ${step.number}: ${step.title}');
///   print('  ${step.description}');
/// }
///
/// // Use in stepper widget
/// Stepper(
///   steps: ActivationStep.values.map((step) => Step(
///     title: Text(step.title),
///     subtitle: Text(step.description),
///     isActive: currentStep == step.number,
///   )).toList(),
/// );
/// ```
enum ActivationStep {
  /// Step 1: Complete training modules.
  ///
  /// Doers must watch training videos and/or read training materials
  /// covering platform policies, quality guidelines, and work expectations.
  training(1, 'Training', 'Complete training modules'),

  /// Step 2: Pass the activation quiz.
  ///
  /// Doers must demonstrate understanding of platform policies and
  /// work quality standards by scoring 80% or higher.
  quiz(2, 'Quiz', 'Pass the interview quiz'),

  /// Step 3: Submit bank account details.
  ///
  /// Doers must provide valid bank account information to receive
  /// payments for completed projects.
  bankDetails(3, 'Bank Details', 'Submit bank account details');

  /// The step number (1, 2, or 3).
  final int number;

  /// The display title for this step.
  final String title;

  /// A brief description of what this step requires.
  final String description;

  /// Creates an [ActivationStep] with the given values.
  const ActivationStep(this.number, this.title, this.description);
}

// =============================================================================
// Activation State
// =============================================================================

/// Full activation state for use in the UI layer.
///
/// This model combines the database [ActivationStatus] with fetched training
/// modules, quiz questions, and bank details. It also includes loading state
/// and error handling.
///
/// ## Usage with Provider
///
/// ```dart
/// class ActivationProvider extends ChangeNotifier {
///   ActivationState _state = ActivationState(
///     status: initialStatus,
///     isLoading: true,
///   );
///
///   ActivationState get state => _state;
///
///   Future<void> loadActivationData() async {
///     _state = _state.copyWith(isLoading: true);
///     notifyListeners();
///
///     try {
///       final modules = await fetchTrainingModules();
///       final questions = await fetchQuizQuestions();
///
///       _state = _state.copyWith(
///         trainingModules: modules,
///         quizQuestions: questions,
///         isLoading: false,
///       );
///     } catch (e) {
///       _state = _state.copyWith(
///         errorMessage: e.toString(),
///         isLoading: false,
///       );
///     }
///     notifyListeners();
///   }
/// }
/// ```
///
/// ## See Also
///
/// - [ActivationStatus] for the database model
/// - [TrainingModule] and [TrainingProgress] for training data
/// - [QuizQuestion] and [QuizAttempt] for quiz data
/// - [BankDetails] for bank details
class ActivationState {
  /// The current activation status from the database.
  final ActivationStatus status;

  /// List of all training modules to be completed.
  ///
  /// Fetched from the `training_modules` table.
  final List<TrainingModule> trainingModules;

  /// Map of module ID to training progress.
  ///
  /// Tracks the doer's progress through each training module.
  /// Key: module ID, Value: [TrainingProgress] for that module.
  final Map<String, TrainingProgress> trainingProgress;

  /// List of quiz questions for the activation quiz.
  ///
  /// Fetched from the `quiz_questions` table.
  final List<QuizQuestion> quizQuestions;

  /// The doer's most recent quiz attempt, if any.
  ///
  /// Used to show previous results and allow retries.
  final QuizAttempt? lastQuizAttempt;

  /// The doer's submitted bank details, if any.
  ///
  /// `null` if bank details have not been submitted.
  final BankDetails? bankDetails;

  /// Whether activation data is currently being loaded.
  ///
  /// Used to show loading indicators in the UI.
  final bool isLoading;

  /// Error message from the most recent failed operation.
  ///
  /// `null` if no error has occurred.
  /// Cleared when a new operation starts.
  final String? errorMessage;

  /// Creates a new [ActivationState] with the specified values.
  ///
  /// Only [status] is required; other fields have sensible defaults.
  const ActivationState({
    required this.status,
    this.trainingModules = const [],
    this.trainingProgress = const {},
    this.quizQuestions = const [],
    this.lastQuizAttempt,
    this.bankDetails,
    this.isLoading = false,
    this.errorMessage,
  });

  /// Creates a copy of this [ActivationState] with updated fields.
  ///
  /// Note: [errorMessage] is explicitly set to allow clearing errors
  /// by passing `null`.
  ///
  /// @returns A new [ActivationState] instance with the specified changes.
  ActivationState copyWith({
    ActivationStatus? status,
    List<TrainingModule>? trainingModules,
    Map<String, TrainingProgress>? trainingProgress,
    List<QuizQuestion>? quizQuestions,
    QuizAttempt? lastQuizAttempt,
    BankDetails? bankDetails,
    bool? isLoading,
    String? errorMessage,
  }) {
    return ActivationState(
      status: status ?? this.status,
      trainingModules: trainingModules ?? this.trainingModules,
      trainingProgress: trainingProgress ?? this.trainingProgress,
      quizQuestions: quizQuestions ?? this.quizQuestions,
      lastQuizAttempt: lastQuizAttempt ?? this.lastQuizAttempt,
      bankDetails: bankDetails ?? this.bankDetails,
      isLoading: isLoading ?? this.isLoading,
      errorMessage: errorMessage,
    );
  }

  /// Checks if all training modules are completed.
  ///
  /// Returns `true` if every module in [trainingModules] has a corresponding
  /// entry in [trainingProgress] with `isCompleted = true`.
  ///
  /// Returns `false` if there are no training modules.
  ///
  /// @returns `true` if all training is complete.
  bool get allTrainingCompleted {
    if (trainingModules.isEmpty) return false;
    return trainingModules.every((module) {
      final progress = trainingProgress[module.id];
      return progress?.isCompleted ?? false;
    });
  }

  /// Gets the overall training progress as a percentage.
  ///
  /// Calculated as: (completed modules / total modules) * 100.
  /// Returns 0 if there are no training modules.
  ///
  /// @returns A double from 0.0 to 100.0.
  ///
  /// ## Example
  ///
  /// ```dart
  /// final percent = state.trainingProgressPercent;
  /// CircularProgressIndicator(value: percent / 100);
  /// Text('${percent.toStringAsFixed(0)}% complete');
  /// ```
  double get trainingProgressPercent {
    if (trainingModules.isEmpty) return 0;
    int completed = 0;
    for (final module in trainingModules) {
      if (trainingProgress[module.id]?.isCompleted ?? false) {
        completed++;
      }
    }
    return (completed / trainingModules.length) * 100;
  }
}
