// Copyright 2024 Doer App. All rights reserved.
// Use of this source code is governed by a BSD-style license.

/// Bank details models for the Doer application.
///
/// This file contains models for managing bank account information
/// used for paying doers for completed projects.
///
/// ## Security Considerations
///
/// Bank details are sensitive information and should be:
/// - Masked when displayed (use [maskedAccountNumber], [maskedIfsc], [maskedUpi])
/// - Transmitted over HTTPS only
/// - Stored encrypted in the database
/// - Access-controlled via RLS policies
///
/// ## Models in this file
///
/// - [BankDetails] - Database model for stored bank account information
/// - [BankDetailsFormData] - Form data model with validation
library bank_details_model;

import '../../shared/utils/masking_utils.dart';

/// Bank details model representing stored bank account information.
///
/// This model maps to bank details stored in the `doers` table or a separate
/// `bank_details` table. It includes the account holder's name, account number,
/// IFSC code, and optional UPI ID.
///
/// ## JSON Structure
///
/// ```json
/// {
///   "id": "bank-details-uuid",
///   "doer_id": "doer-uuid",
///   "account_holder_name": "John Doe",
///   "account_number": "1234567890123456",
///   "ifsc_code": "SBIN0001234",
///   "bank_name": "State Bank of India",
///   "branch_name": "Mumbai Main Branch",
///   "upi_id": "john@upi",
///   "is_verified": true,
///   "created_at": "2024-01-01T00:00:00Z",
///   "updated_at": "2024-01-15T10:30:00Z"
/// }
/// ```
///
/// ## Usage
///
/// ```dart
/// // Parse from database
/// final bankDetails = BankDetails.fromJson(jsonData);
///
/// // Display masked values for security
/// Text('Account: ${bankDetails.maskedAccountNumber}');
/// Text('IFSC: ${bankDetails.maskedIfsc}');
///
/// // Check verification status
/// if (bankDetails.isVerified) {
///   showVerifiedBadge();
/// }
/// ```
///
/// ## See Also
///
/// - [BankDetailsFormData] for form input handling
/// - [MaskingUtils] for the masking implementation
class BankDetails {
  /// Unique identifier for this bank details record.
  ///
  /// UUID generated by the database.
  final String id;

  /// Reference to the doer whose bank details these are.
  ///
  /// Foreign key to `doers.id`.
  final String doerId;

  /// Name of the bank account holder.
  ///
  /// Should match the name on the bank account exactly
  /// for successful fund transfers.
  final String accountHolderName;

  /// Bank account number.
  ///
  /// Sensitive data - should be masked when displayed.
  /// Typically 9-18 digits depending on the bank.
  final String accountNumber;

  /// IFSC code of the bank branch.
  ///
  /// 11-character code identifying the bank and branch.
  /// Format: `ABCD0123456` (4 letters + 0 + 6 alphanumeric).
  /// Used for NEFT/RTGS/IMPS transfers.
  final String ifscCode;

  /// Name of the bank.
  ///
  /// Can be auto-populated from IFSC code lookup or manually entered.
  /// Examples: `'State Bank of India'`, `'HDFC Bank'`.
  final String? bankName;

  /// Name of the bank branch.
  ///
  /// Optional. Can be auto-populated from IFSC code lookup.
  final String? branchName;

  /// UPI ID for instant payments.
  ///
  /// Optional alternative to bank transfer.
  /// Format: `username@upi` or `phonenumber@bank`.
  /// Examples: `'john@upi'`, `'9876543210@ybl'`.
  final String? upiId;

  /// Whether the bank details have been verified.
  ///
  /// Verification may be done via:
  /// - Penny drop (small test transaction)
  /// - IFSC code validation
  /// - Manual review
  ///
  /// Unverified bank details may cause payment delays.
  final bool isVerified;

  /// Timestamp when the bank details were first submitted.
  ///
  /// Set by the database on insert.
  final DateTime createdAt;

  /// Timestamp when the bank details were last updated.
  ///
  /// `null` if never updated after creation.
  final DateTime? updatedAt;

  /// Creates a new [BankDetails] with the specified values.
  ///
  /// Required parameters:
  /// - [id]: Unique record identifier
  /// - [doerId]: Reference to the doer
  /// - [accountHolderName]: Name on the bank account
  /// - [accountNumber]: Bank account number
  /// - [ifscCode]: IFSC code of the branch
  /// - [createdAt]: Creation timestamp
  const BankDetails({
    required this.id,
    required this.doerId,
    required this.accountHolderName,
    required this.accountNumber,
    required this.ifscCode,
    this.bankName,
    this.branchName,
    this.upiId,
    this.isVerified = false,
    required this.createdAt,
    this.updatedAt,
  });

  /// Creates a [BankDetails] from a JSON map (database response).
  ///
  /// @param json The JSON map from the database response.
  /// @returns A new [BankDetails] instance.
  factory BankDetails.fromJson(Map<String, dynamic> json) {
    return BankDetails(
      id: json['id'] as String,
      doerId: json['doer_id'] as String,
      accountHolderName: json['account_holder_name'] as String,
      accountNumber: json['account_number'] as String,
      ifscCode: json['ifsc_code'] as String,
      bankName: json['bank_name'] as String?,
      branchName: json['branch_name'] as String?,
      upiId: json['upi_id'] as String?,
      isVerified: json['is_verified'] as bool? ?? false,
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: json['updated_at'] != null
          ? DateTime.parse(json['updated_at'] as String)
          : null,
    );
  }

  /// Converts this [BankDetails] to a JSON map.
  ///
  /// @returns A map of column names to values.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'doer_id': doerId,
      'account_holder_name': accountHolderName,
      'account_number': accountNumber,
      'ifsc_code': ifscCode,
      'bank_name': bankName,
      'branch_name': branchName,
      'upi_id': upiId,
      'is_verified': isVerified,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt?.toIso8601String(),
    };
  }

  /// Creates a copy of this [BankDetails] with updated fields.
  ///
  /// @returns A new [BankDetails] instance with the specified changes.
  BankDetails copyWith({
    String? id,
    String? doerId,
    String? accountHolderName,
    String? accountNumber,
    String? ifscCode,
    String? bankName,
    String? branchName,
    String? upiId,
    bool? isVerified,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return BankDetails(
      id: id ?? this.id,
      doerId: doerId ?? this.doerId,
      accountHolderName: accountHolderName ?? this.accountHolderName,
      accountNumber: accountNumber ?? this.accountNumber,
      ifscCode: ifscCode ?? this.ifscCode,
      bankName: bankName ?? this.bankName,
      branchName: branchName ?? this.branchName,
      upiId: upiId ?? this.upiId,
      isVerified: isVerified ?? this.isVerified,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  /// Gets a masked version of the account number for display.
  ///
  /// Shows only the last 4 digits, with the rest replaced by asterisks.
  /// Example: `'1234567890123456'` becomes `'************3456'`.
  ///
  /// @returns Masked account number string.
  String get maskedAccountNumber => MaskingUtils.maskAccountNumber(accountNumber);

  /// Gets a masked version of the IFSC code for display.
  ///
  /// Shows the bank code (first 4 chars) and masks the rest.
  /// Example: `'SBIN0001234'` becomes `'SBIN*******'`.
  ///
  /// @returns Masked IFSC code string.
  String get maskedIfsc => MaskingUtils.maskIFSC(ifscCode);

  /// Gets a masked version of the UPI ID for display.
  ///
  /// Masks the middle portion of the UPI ID.
  /// Returns `null` if no UPI ID is set.
  ///
  /// @returns Masked UPI ID string, or `null`.
  String? get maskedUpi => upiId != null ? MaskingUtils.maskUPI(upiId!) : null;
}

// =============================================================================
// Bank Details Form Data
// =============================================================================

/// Form data model for bank details submission.
///
/// Used to collect and validate bank details from the user before
/// submitting to the database. Includes a confirmation field to
/// prevent account number typos.
///
/// ## Validation Rules
///
/// The [isValid] getter checks:
/// - Account holder name is not empty
/// - Account number is not empty
/// - Account number matches confirmation
/// - IFSC code is exactly 11 characters
///
/// ## Usage
///
/// ```dart
/// final formData = BankDetailsFormData(
///   accountHolderName: nameController.text,
///   accountNumber: accountController.text,
///   confirmAccountNumber: confirmController.text,
///   ifscCode: ifscController.text,
///   upiId: upiController.text.isNotEmpty ? upiController.text : null,
/// );
///
/// if (formData.isValid) {
///   await saveBankDetails(formData.toJson());
/// } else {
///   showValidationError();
/// }
/// ```
///
/// ## See Also
///
/// - [BankDetails] for the database model
class BankDetailsFormData {
  /// Name of the bank account holder.
  ///
  /// Should match the name on the bank account exactly.
  final String accountHolderName;

  /// Bank account number.
  ///
  /// Typically 9-18 digits depending on the bank.
  final String accountNumber;

  /// Confirmation entry of the account number.
  ///
  /// Must exactly match [accountNumber] for form validation.
  /// Used to prevent typos when entering account numbers.
  final String confirmAccountNumber;

  /// IFSC code of the bank branch.
  ///
  /// Must be exactly 11 characters.
  /// Format: 4 letters + 0 + 6 alphanumeric.
  final String ifscCode;

  /// UPI ID for instant payments (optional).
  ///
  /// Alternative payment method.
  /// Format: `username@upi` or `phonenumber@bank`.
  final String? upiId;

  /// Creates a new [BankDetailsFormData] with the specified values.
  ///
  /// Required parameters:
  /// - [accountHolderName]: Name on the bank account
  /// - [accountNumber]: Bank account number
  /// - [confirmAccountNumber]: Account number confirmation
  /// - [ifscCode]: IFSC code of the branch
  const BankDetailsFormData({
    required this.accountHolderName,
    required this.accountNumber,
    required this.confirmAccountNumber,
    required this.ifscCode,
    this.upiId,
  });

  /// Converts this form data to a JSON map for database insert.
  ///
  /// Note: Does not include [confirmAccountNumber] as it's only
  /// used for validation.
  ///
  /// @returns A map of column names to values.
  Map<String, dynamic> toJson() {
    return {
      'account_holder_name': accountHolderName,
      'account_number': accountNumber,
      'ifsc_code': ifscCode,
      'upi_id': upiId,
    };
  }

  /// Validates the form data.
  ///
  /// Returns `true` if all validation rules pass:
  /// - Account holder name is not empty
  /// - Account number is not empty
  /// - Account number matches confirmation
  /// - IFSC code is not empty
  /// - IFSC code is exactly 11 characters
  ///
  /// @returns `true` if form data is valid and ready for submission.
  ///
  /// ## Example
  ///
  /// ```dart
  /// if (formData.isValid) {
  ///   submitButton.enable();
  /// } else {
  ///   submitButton.disable();
  /// }
  /// ```
  bool get isValid =>
      accountHolderName.isNotEmpty &&
      accountNumber.isNotEmpty &&
      accountNumber == confirmAccountNumber &&
      ifscCode.isNotEmpty &&
      ifscCode.length == 11;
}
