// Copyright 2024 Doer App. All rights reserved.
// Use of this source code is governed by a BSD-style license.

/// Doer-specific models for the Doer application.
///
/// This file contains models representing doer-specific data stored in the
/// `doers` table and related junction tables for skills and subjects.
///
/// ## Models in this file
///
/// - [DoerModel] - Doer profile with qualifications, experience, and stats
/// - [SkillModel] - Skills that doers can possess
/// - [SubjectModel] - Academic subjects doers specialize in
/// - [DoerSkillModel] - Junction table linking doers to skills
/// - [DoerSubjectModel] - Junction table linking doers to subjects
///
/// ## Database Schema
///
/// ```
/// doers
///   ├── id (PK)
///   ├── profile_id (FK -> profiles.id)
///   ├── qualification, experience_level, years_of_experience
///   ├── bank details (account_name, account_number, ifsc_code, etc.)
///   ├── performance stats (total_projects, earnings, rating)
///   └── activation & flag status
///
/// skills
///   ├── id (PK)
///   ├── name, slug, category
///   └── subject_id (FK -> subjects.id, optional)
///
/// subjects
///   ├── id (PK)
///   ├── name, slug, description
///   └── parent_id (FK -> subjects.id, for hierarchical subjects)
///
/// doer_skills (junction)
///   ├── doer_id (FK -> doers.id)
///   ├── skill_id (FK -> skills.id)
///   └── proficiency_level, verification status
///
/// doer_subjects (junction)
///   ├── doer_id (FK -> doers.id)
///   ├── subject_id (FK -> subjects.id)
///   └── is_primary (marks main area of expertise)
/// ```
library doer_model;

/// Doer model representing doer-specific data in the `doers` table.
///
/// This model extends the base profile with doer-specific fields including
/// qualifications, experience, bank details, performance statistics, and
/// moderation flags. Each doer record is linked to a profile via [profileId].
///
/// ## JSON Structure
///
/// ```json
/// {
///   "id": "doer-uuid",
///   "profile_id": "profile-uuid",
///   "qualification": "B.Tech",
///   "university_name": "IIT Mumbai",
///   "experience_level": "intermediate",
///   "years_of_experience": 2,
///   "bio": "Experienced academic writer...",
///   "is_available": true,
///   "max_concurrent_projects": 3,
///   "is_activated": true,
///   "activated_at": "2024-01-15T10:30:00Z",
///   "total_projects_completed": 25,
///   "total_earnings": 50000.00,
///   "average_rating": 4.8,
///   "bank_account_name": "John Doe",
///   "bank_account_number": "1234567890",
///   "bank_ifsc_code": "SBIN0001234",
///   "bank_verified": true,
///   "is_flagged": false,
///   "created_at": "2024-01-01T00:00:00Z"
/// }
/// ```
///
/// ## Usage
///
/// ```dart
/// // Parse from database response
/// final doer = DoerModel.fromJson(jsonData);
///
/// // Create insert data for new doer
/// final insertData = DoerModel.createInsertData(
///   profileId: 'profile-uuid',
///   qualification: 'B.Tech',
///   experienceLevel: 'beginner',
/// );
///
/// // Update bank details
/// final bankUpdate = DoerModel.createBankDetailsUpdate(
///   accountName: 'John Doe',
///   accountNumber: '1234567890',
///   ifscCode: 'SBIN0001234',
/// );
/// ```
///
/// ## See Also
///
/// - [ProfileModel] for the base profile this extends
/// - [UserModel] for the combined view used in UI
/// - [SkillModel] and [SubjectModel] for doer capabilities
class DoerModel {
  /// Unique identifier for the doer record.
  ///
  /// UUID generated by the database. This is different from the profile ID.
  final String id;

  /// Reference to the associated profile.
  ///
  /// Foreign key linking to `profiles.id`. Each doer has exactly one profile.
  final String profileId;

  /// Doer's highest educational qualification.
  ///
  /// Required field. Examples: `'B.Tech'`, `'M.Sc'`, `'PhD'`, `'12th Pass'`.
  /// Used for matching with project requirements.
  final String qualification;

  /// Name of the university or institution attended.
  ///
  /// Optional. Adds credibility to the doer's profile.
  final String? universityName;

  /// Doer's experience level in academic/professional work.
  ///
  /// Valid values: `'beginner'`, `'intermediate'`, `'expert'`.
  /// Affects project matching, visibility, and pricing tiers.
  final String experienceLevel;

  /// Number of years of relevant experience.
  ///
  /// Must be non-negative. Combined with [experienceLevel] for matching.
  /// Defaults to 0 for new doers.
  final int yearsOfExperience;

  /// Doer's bio or self-introduction.
  ///
  /// Optional free-text field. Displayed on profile and to supervisors
  /// when reviewing doer applications.
  final String? bio;

  /// Whether the doer is currently available for new projects.
  ///
  /// When `false`, the doer won't receive new project assignments.
  /// Useful for vacation or temporary unavailability.
  final bool isAvailable;

  /// Timestamp when availability was last updated.
  ///
  /// Tracked to monitor doer activity patterns.
  final DateTime? availabilityUpdatedAt;

  /// Maximum number of projects the doer can work on simultaneously.
  ///
  /// Prevents overcommitment. Defaults to 3.
  /// Supervisors can adjust this based on doer performance.
  final int maxConcurrentProjects;

  /// Whether the doer has completed the activation process.
  ///
  /// Activation requires: training completion, quiz pass, bank details.
  /// Only activated doers can accept and work on projects.
  final bool isActivated;

  /// Timestamp when the doer was fully activated.
  ///
  /// `null` if not yet activated.
  final DateTime? activatedAt;

  // ═══════════════════════════════════════════════════════════════════════════
  // Performance Statistics
  // ═══════════════════════════════════════════════════════════════════════════

  /// Total number of projects successfully completed.
  ///
  /// Incremented when a project reaches `'completed'` or `'paid'` status.
  /// Used for ranking and trust scoring.
  final int totalProjectsCompleted;

  /// Total earnings accumulated in INR.
  ///
  /// Sum of all payments received for completed projects.
  /// Updated when projects are marked as paid.
  final double totalEarnings;

  /// Average rating from project reviews (0.0 to 5.0).
  ///
  /// Calculated as the mean of all review ratings.
  /// `0.0` if no reviews yet. Updated after each new review.
  final double averageRating;

  /// Total number of reviews received.
  ///
  /// Count of all project reviews. Used with [averageRating]
  /// to calculate weighted scores.
  final int totalReviews;

  /// Percentage of successfully completed projects.
  ///
  /// Calculated as: (completed / total accepted) * 100.
  /// Defaults to 100.0 for new doers.
  final double successRate;

  /// Percentage of projects delivered on time.
  ///
  /// Calculated as: (on-time deliveries / total completed) * 100.
  /// Defaults to 100.0 for new doers.
  final double onTimeDeliveryRate;

  // ═══════════════════════════════════════════════════════════════════════════
  // Bank Details
  // ═══════════════════════════════════════════════════════════════════════════

  /// Name of the bank account holder.
  ///
  /// Should match the name on the bank account for successful transfers.
  /// Required for payment processing.
  final String? bankAccountName;

  /// Bank account number.
  ///
  /// Sensitive data - should be masked when displayed.
  /// Typically 9-18 digits depending on the bank.
  final String? bankAccountNumber;

  /// IFSC code of the bank branch.
  ///
  /// 11-character code identifying the bank and branch.
  /// Format: `ABCD0123456` (4 letters + 0 + 6 alphanumeric).
  final String? bankIfscCode;

  /// Name of the bank.
  ///
  /// Can be auto-populated from IFSC lookup or manually entered.
  final String? bankName;

  /// UPI ID for instant payments.
  ///
  /// Optional alternative to bank transfer.
  /// Format: `username@upi` or `phonenumber@bank`.
  final String? upiId;

  /// Whether the bank details have been verified.
  ///
  /// Verification may be done via penny drop or manual review.
  /// Unverified bank details may have payment delays.
  final bool bankVerified;

  // ═══════════════════════════════════════════════════════════════════════════
  // Moderation Flags
  // ═══════════════════════════════════════════════════════════════════════════

  /// Whether the doer account is currently flagged for review.
  ///
  /// Flagged doers may have restricted access to new projects.
  final bool isFlagged;

  /// Reason for flagging the account.
  ///
  /// Set by moderators when [isFlagged] is `true`.
  /// Examples: `'Quality issues'`, `'Late deliveries'`, `'Plagiarism'`.
  final String? flagReason;

  /// ID of the admin/supervisor who flagged the account.
  ///
  /// Reference to the profile ID of the moderator.
  final String? flaggedBy;

  /// Timestamp when the account was flagged.
  ///
  /// `null` if not currently flagged.
  final DateTime? flaggedAt;

  // ═══════════════════════════════════════════════════════════════════════════
  // Timestamps
  // ═══════════════════════════════════════════════════════════════════════════

  /// Timestamp when the doer record was created.
  ///
  /// Set automatically by the database on insert.
  final DateTime createdAt;

  /// Timestamp when the doer record was last updated.
  ///
  /// `null` if never updated after creation.
  final DateTime? updatedAt;

  /// Creates a new [DoerModel] with the specified values.
  ///
  /// Required parameters:
  /// - [id]: Unique doer identifier
  /// - [profileId]: Reference to associated profile
  /// - [qualification]: Educational qualification
  /// - [experienceLevel]: Experience level (beginner/intermediate/expert)
  /// - [createdAt]: Creation timestamp
  const DoerModel({
    required this.id,
    required this.profileId,
    required this.qualification,
    this.universityName,
    required this.experienceLevel,
    this.yearsOfExperience = 0,
    this.bio,
    this.isAvailable = true,
    this.availabilityUpdatedAt,
    this.maxConcurrentProjects = 3,
    this.isActivated = false,
    this.activatedAt,
    this.totalProjectsCompleted = 0,
    this.totalEarnings = 0.0,
    this.averageRating = 0.0,
    this.totalReviews = 0,
    this.successRate = 100.0,
    this.onTimeDeliveryRate = 100.0,
    this.bankAccountName,
    this.bankAccountNumber,
    this.bankIfscCode,
    this.bankName,
    this.upiId,
    this.bankVerified = false,
    this.isFlagged = false,
    this.flagReason,
    this.flaggedBy,
    this.flaggedAt,
    required this.createdAt,
    this.updatedAt,
  });

  /// Creates a [DoerModel] from a JSON map (database response).
  ///
  /// Parses all fields from the database response, applying default values
  /// for optional fields that may be null.
  ///
  /// @param json The JSON map from the database response.
  /// @returns A new [DoerModel] instance populated from the JSON data.
  ///
  /// @throws FormatException if required fields are missing or malformed.
  factory DoerModel.fromJson(Map<String, dynamic> json) {
    return DoerModel(
      id: json['id'] as String,
      profileId: json['profile_id'] as String,
      qualification: json['qualification'] as String,
      universityName: json['university_name'] as String?,
      experienceLevel: json['experience_level'] as String,
      yearsOfExperience: json['years_of_experience'] as int? ?? 0,
      bio: json['bio'] as String?,
      isAvailable: json['is_available'] as bool? ?? true,
      availabilityUpdatedAt: json['availability_updated_at'] != null
          ? DateTime.parse(json['availability_updated_at'] as String)
          : null,
      maxConcurrentProjects: json['max_concurrent_projects'] as int? ?? 3,
      isActivated: json['is_activated'] as bool? ?? false,
      activatedAt: json['activated_at'] != null
          ? DateTime.parse(json['activated_at'] as String)
          : null,
      totalProjectsCompleted: json['total_projects_completed'] as int? ?? 0,
      totalEarnings: (json['total_earnings'] as num?)?.toDouble() ?? 0.0,
      averageRating: (json['average_rating'] as num?)?.toDouble() ?? 0.0,
      totalReviews: json['total_reviews'] as int? ?? 0,
      successRate: (json['success_rate'] as num?)?.toDouble() ?? 100.0,
      onTimeDeliveryRate: (json['on_time_delivery_rate'] as num?)?.toDouble() ?? 100.0,
      bankAccountName: json['bank_account_name'] as String?,
      bankAccountNumber: json['bank_account_number'] as String?,
      bankIfscCode: json['bank_ifsc_code'] as String?,
      bankName: json['bank_name'] as String?,
      upiId: json['upi_id'] as String?,
      bankVerified: json['bank_verified'] as bool? ?? false,
      isFlagged: json['is_flagged'] as bool? ?? false,
      flagReason: json['flag_reason'] as String?,
      flaggedBy: json['flagged_by'] as String?,
      flaggedAt: json['flagged_at'] != null
          ? DateTime.parse(json['flagged_at'] as String)
          : null,
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: json['updated_at'] != null
          ? DateTime.parse(json['updated_at'] as String)
          : null,
    );
  }

  /// Converts this [DoerModel] to a JSON map for database insert/update.
  ///
  /// Includes all fields with their current values. DateTime fields are
  /// converted to ISO 8601 strings.
  ///
  /// @returns A map of column names to values.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'profile_id': profileId,
      'qualification': qualification,
      'university_name': universityName,
      'experience_level': experienceLevel,
      'years_of_experience': yearsOfExperience,
      'bio': bio,
      'is_available': isAvailable,
      'availability_updated_at': availabilityUpdatedAt?.toIso8601String(),
      'max_concurrent_projects': maxConcurrentProjects,
      'is_activated': isActivated,
      'activated_at': activatedAt?.toIso8601String(),
      'total_projects_completed': totalProjectsCompleted,
      'total_earnings': totalEarnings,
      'average_rating': averageRating,
      'total_reviews': totalReviews,
      'success_rate': successRate,
      'on_time_delivery_rate': onTimeDeliveryRate,
      'bank_account_name': bankAccountName,
      'bank_account_number': bankAccountNumber,
      'bank_ifsc_code': bankIfscCode,
      'bank_name': bankName,
      'upi_id': upiId,
      'bank_verified': bankVerified,
      'is_flagged': isFlagged,
      'flag_reason': flagReason,
      'flagged_by': flaggedBy,
      'flagged_at': flaggedAt?.toIso8601String(),
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt?.toIso8601String(),
    };
  }

  /// Creates insert data for a new doer record.
  ///
  /// Generates a minimal map with only the required and provided optional
  /// fields. Uses conditional inclusion to avoid inserting null values.
  ///
  /// @param profileId The profile UUID to link this doer to (required).
  /// @param qualification The doer's educational qualification (required).
  /// @param experienceLevel Experience level: beginner/intermediate/expert (required).
  /// @param universityName Name of institution attended (optional).
  /// @param bio Self-introduction text (optional).
  /// @returns A map suitable for Supabase insert operation.
  ///
  /// ## Example
  ///
  /// ```dart
  /// final insertData = DoerModel.createInsertData(
  ///   profileId: 'profile-uuid',
  ///   qualification: 'B.Tech',
  ///   experienceLevel: 'beginner',
  ///   universityName: 'IIT Mumbai',
  /// );
  /// await supabase.from('doers').insert(insertData);
  /// ```
  static Map<String, dynamic> createInsertData({
    required String profileId,
    required String qualification,
    required String experienceLevel,
    String? universityName,
    String? bio,
  }) {
    return {
      'profile_id': profileId,
      'qualification': qualification,
      'experience_level': experienceLevel,
      if (universityName != null) 'university_name': universityName,
      if (bio != null) 'bio': bio,
    };
  }

  /// Creates update data for bank details fields.
  ///
  /// Generates a map containing only bank-related fields suitable for
  /// a partial update operation.
  ///
  /// @param accountName Name of the account holder (required).
  /// @param accountNumber Bank account number (required).
  /// @param ifscCode IFSC code of the bank branch (required).
  /// @param bankName Name of the bank (optional).
  /// @param upiId UPI ID for instant payments (optional).
  /// @returns A map suitable for Supabase update operation.
  ///
  /// ## Example
  ///
  /// ```dart
  /// final bankUpdate = DoerModel.createBankDetailsUpdate(
  ///   accountName: 'John Doe',
  ///   accountNumber: '1234567890',
  ///   ifscCode: 'SBIN0001234',
  ///   bankName: 'State Bank of India',
  /// );
  /// await supabase.from('doers').update(bankUpdate).eq('id', doerId);
  /// ```
  static Map<String, dynamic> createBankDetailsUpdate({
    required String accountName,
    required String accountNumber,
    required String ifscCode,
    String? bankName,
    String? upiId,
  }) {
    return {
      'bank_account_name': accountName,
      'bank_account_number': accountNumber,
      'bank_ifsc_code': ifscCode,
      if (bankName != null) 'bank_name': bankName,
      if (upiId != null) 'upi_id': upiId,
    };
  }

  /// Whether bank details have been submitted.
  ///
  /// Returns `true` if all required bank fields are present:
  /// [bankAccountName], [bankAccountNumber], and [bankIfscCode].
  ///
  /// Note: This doesn't indicate verification status - check [bankVerified]
  /// for that.
  bool get hasBankDetails =>
      bankAccountName != null &&
      bankAccountNumber != null &&
      bankIfscCode != null;

  /// Creates a copy of this [DoerModel] with updated fields.
  ///
  /// All parameters are optional. Omitted parameters retain their
  /// original values.
  ///
  /// @returns A new [DoerModel] instance with the specified changes.
  ///
  /// ## Example
  ///
  /// ```dart
  /// final updatedDoer = doer.copyWith(
  ///   isActivated: true,
  ///   activatedAt: DateTime.now(),
  /// );
  /// ```
  DoerModel copyWith({
    String? id,
    String? profileId,
    String? qualification,
    String? universityName,
    String? experienceLevel,
    int? yearsOfExperience,
    String? bio,
    bool? isAvailable,
    DateTime? availabilityUpdatedAt,
    int? maxConcurrentProjects,
    bool? isActivated,
    DateTime? activatedAt,
    int? totalProjectsCompleted,
    double? totalEarnings,
    double? averageRating,
    int? totalReviews,
    double? successRate,
    double? onTimeDeliveryRate,
    String? bankAccountName,
    String? bankAccountNumber,
    String? bankIfscCode,
    String? bankName,
    String? upiId,
    bool? bankVerified,
    bool? isFlagged,
    String? flagReason,
    String? flaggedBy,
    DateTime? flaggedAt,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return DoerModel(
      id: id ?? this.id,
      profileId: profileId ?? this.profileId,
      qualification: qualification ?? this.qualification,
      universityName: universityName ?? this.universityName,
      experienceLevel: experienceLevel ?? this.experienceLevel,
      yearsOfExperience: yearsOfExperience ?? this.yearsOfExperience,
      bio: bio ?? this.bio,
      isAvailable: isAvailable ?? this.isAvailable,
      availabilityUpdatedAt: availabilityUpdatedAt ?? this.availabilityUpdatedAt,
      maxConcurrentProjects: maxConcurrentProjects ?? this.maxConcurrentProjects,
      isActivated: isActivated ?? this.isActivated,
      activatedAt: activatedAt ?? this.activatedAt,
      totalProjectsCompleted: totalProjectsCompleted ?? this.totalProjectsCompleted,
      totalEarnings: totalEarnings ?? this.totalEarnings,
      averageRating: averageRating ?? this.averageRating,
      totalReviews: totalReviews ?? this.totalReviews,
      successRate: successRate ?? this.successRate,
      onTimeDeliveryRate: onTimeDeliveryRate ?? this.onTimeDeliveryRate,
      bankAccountName: bankAccountName ?? this.bankAccountName,
      bankAccountNumber: bankAccountNumber ?? this.bankAccountNumber,
      bankIfscCode: bankIfscCode ?? this.bankIfscCode,
      bankName: bankName ?? this.bankName,
      upiId: upiId ?? this.upiId,
      bankVerified: bankVerified ?? this.bankVerified,
      isFlagged: isFlagged ?? this.isFlagged,
      flagReason: flagReason ?? this.flagReason,
      flaggedBy: flaggedBy ?? this.flaggedBy,
      flaggedAt: flaggedAt ?? this.flaggedAt,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  @override
  String toString() {
    return 'DoerModel(id: $id, profileId: $profileId, qualification: $qualification, isActivated: $isActivated)';
  }
}

// =============================================================================
// Skill Model
// =============================================================================

/// Skill model representing a skill from the `skills` table.
///
/// Skills are specific capabilities that doers can possess, such as
/// "Essay Writing", "Research", "Data Analysis", etc.
///
/// ## JSON Structure
///
/// ```json
/// {
///   "id": "skill-uuid",
///   "name": "Essay Writing",
///   "slug": "essay-writing",
///   "category": "writing",
///   "subject_id": "subject-uuid",
///   "is_active": true
/// }
/// ```
///
/// ## Usage
///
/// ```dart
/// final skill = SkillModel.fromJson(jsonData);
/// print('Skill: ${skill.name} (${skill.category})');
/// ```
///
/// ## See Also
///
/// - [DoerSkillModel] for the junction table linking doers to skills
/// - [SubjectModel] for related academic subjects
class SkillModel {
  /// Unique identifier for the skill.
  ///
  /// UUID generated by the database.
  final String id;

  /// Display name of the skill.
  ///
  /// Human-readable name shown in the UI.
  /// Examples: `'Essay Writing'`, `'Data Analysis'`.
  final String name;

  /// URL-friendly identifier for the skill.
  ///
  /// Lowercase, hyphenated version of the name.
  /// Examples: `'essay-writing'`, `'data-analysis'`.
  final String slug;

  /// Category grouping for the skill.
  ///
  /// Used to organize skills in the UI.
  /// Examples: `'writing'`, `'research'`, `'technical'`.
  final String? category;

  /// Reference to an associated subject, if applicable.
  ///
  /// Some skills are subject-specific (e.g., "Java Programming"
  /// belongs to "Computer Science").
  final String? subjectId;

  /// Whether the skill is currently active in the system.
  ///
  /// Inactive skills won't appear in selection lists.
  final bool isActive;

  /// Creates a new [SkillModel] with the specified values.
  ///
  /// Required parameters:
  /// - [id]: Unique skill identifier
  /// - [name]: Display name
  /// - [slug]: URL-friendly identifier
  const SkillModel({
    required this.id,
    required this.name,
    required this.slug,
    this.category,
    this.subjectId,
    this.isActive = true,
  });

  /// Creates a [SkillModel] from a JSON map.
  ///
  /// @param json The JSON map from the database response.
  /// @returns A new [SkillModel] instance.
  factory SkillModel.fromJson(Map<String, dynamic> json) {
    return SkillModel(
      id: json['id'] as String,
      name: json['name'] as String,
      slug: json['slug'] as String,
      category: json['category'] as String?,
      subjectId: json['subject_id'] as String?,
      isActive: json['is_active'] as bool? ?? true,
    );
  }

  /// Converts this [SkillModel] to a JSON map.
  ///
  /// @returns A map of column names to values.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'slug': slug,
      'category': category,
      'subject_id': subjectId,
      'is_active': isActive,
    };
  }
}

// =============================================================================
// Subject Model
// =============================================================================

/// Subject model representing an academic subject from the `subjects` table.
///
/// Subjects are academic areas that doers can specialize in, such as
/// "Computer Science", "Mathematics", "English Literature", etc.
/// Subjects can be hierarchical with parent-child relationships.
///
/// ## JSON Structure
///
/// ```json
/// {
///   "id": "subject-uuid",
///   "name": "Computer Science",
///   "slug": "computer-science",
///   "description": "Study of computation and information",
///   "icon": "computer",
///   "parent_id": null,
///   "category": "science",
///   "display_order": 1,
///   "is_active": true
/// }
/// ```
///
/// ## Usage
///
/// ```dart
/// final subject = SubjectModel.fromJson(jsonData);
/// print('Subject: ${subject.name}');
/// if (subject.parentId != null) {
///   print('This is a sub-subject');
/// }
/// ```
///
/// ## See Also
///
/// - [DoerSubjectModel] for the junction table linking doers to subjects
/// - [SkillModel] for related skills
class SubjectModel {
  /// Unique identifier for the subject.
  ///
  /// UUID generated by the database.
  final String id;

  /// Display name of the subject.
  ///
  /// Human-readable name shown in the UI.
  /// Examples: `'Computer Science'`, `'Mathematics'`.
  final String name;

  /// URL-friendly identifier for the subject.
  ///
  /// Lowercase, hyphenated version of the name.
  /// Examples: `'computer-science'`, `'mathematics'`.
  final String slug;

  /// Detailed description of the subject.
  ///
  /// Optional. Explains what the subject covers.
  final String? description;

  /// Icon identifier for the subject.
  ///
  /// Can be a Material icon name or custom icon identifier.
  final String? icon;

  /// Reference to a parent subject for hierarchical organization.
  ///
  /// `null` for top-level subjects. Used to create subject trees
  /// (e.g., "Programming" under "Computer Science").
  final String? parentId;

  /// Category grouping for the subject.
  ///
  /// Used for organizing subjects in the UI.
  /// Examples: `'science'`, `'arts'`, `'commerce'`.
  final String? category;

  /// Order in which to display this subject.
  ///
  /// Lower numbers appear first. Used for consistent ordering.
  final int? displayOrder;

  /// Whether the subject is currently active in the system.
  ///
  /// Inactive subjects won't appear in selection lists.
  final bool isActive;

  /// Creates a new [SubjectModel] with the specified values.
  ///
  /// Required parameters:
  /// - [id]: Unique subject identifier
  /// - [name]: Display name
  /// - [slug]: URL-friendly identifier
  const SubjectModel({
    required this.id,
    required this.name,
    required this.slug,
    this.description,
    this.icon,
    this.parentId,
    this.category,
    this.displayOrder,
    this.isActive = true,
  });

  /// Creates a [SubjectModel] from a JSON map.
  ///
  /// @param json The JSON map from the database response.
  /// @returns A new [SubjectModel] instance.
  factory SubjectModel.fromJson(Map<String, dynamic> json) {
    return SubjectModel(
      id: json['id'] as String,
      name: json['name'] as String,
      slug: json['slug'] as String,
      description: json['description'] as String?,
      icon: json['icon'] as String?,
      parentId: json['parent_id'] as String?,
      category: json['category'] as String?,
      displayOrder: json['display_order'] as int?,
      isActive: json['is_active'] as bool? ?? true,
    );
  }

  /// Converts this [SubjectModel] to a JSON map.
  ///
  /// @returns A map of column names to values.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'slug': slug,
      'description': description,
      'icon': icon,
      'parent_id': parentId,
      'category': category,
      'display_order': displayOrder,
      'is_active': isActive,
    };
  }
}

// =============================================================================
// Junction Models
// =============================================================================

/// Junction model for the `doer_skills` table.
///
/// Links doers to skills with additional metadata like proficiency level
/// and verification status.
///
/// ## JSON Structure
///
/// ```json
/// {
///   "id": "junction-uuid",
///   "doer_id": "doer-uuid",
///   "skill_id": "skill-uuid",
///   "proficiency_level": "intermediate",
///   "is_verified": true,
///   "verified_at": "2024-01-15T10:30:00Z",
///   "verified_by": "admin-uuid",
///   "created_at": "2024-01-01T00:00:00Z"
/// }
/// ```
///
/// ## See Also
///
/// - [DoerModel] for the doer side of the relationship
/// - [SkillModel] for the skill side of the relationship
class DoerSkillModel {
  /// Unique identifier for this junction record.
  final String id;

  /// Reference to the doer.
  ///
  /// Foreign key to `doers.id`.
  final String doerId;

  /// Reference to the skill.
  ///
  /// Foreign key to `skills.id`.
  final String skillId;

  /// Proficiency level for this skill.
  ///
  /// Values: `'beginner'`, `'intermediate'`, `'advanced'`, `'expert'`.
  /// Optional - may be self-reported or assessed.
  final String? proficiencyLevel;

  /// Whether this skill has been verified.
  ///
  /// Verification can be done through tests or manual review.
  final bool isVerified;

  /// Timestamp when the skill was verified.
  ///
  /// `null` if not verified.
  final DateTime? verifiedAt;

  /// ID of the admin/supervisor who verified the skill.
  ///
  /// Reference to a profile ID.
  final String? verifiedBy;

  /// Timestamp when this skill was added to the doer's profile.
  final DateTime createdAt;

  /// Creates a new [DoerSkillModel] with the specified values.
  const DoerSkillModel({
    required this.id,
    required this.doerId,
    required this.skillId,
    this.proficiencyLevel,
    this.isVerified = false,
    this.verifiedAt,
    this.verifiedBy,
    required this.createdAt,
  });

  /// Creates a [DoerSkillModel] from a JSON map.
  ///
  /// @param json The JSON map from the database response.
  /// @returns A new [DoerSkillModel] instance.
  factory DoerSkillModel.fromJson(Map<String, dynamic> json) {
    return DoerSkillModel(
      id: json['id'] as String,
      doerId: json['doer_id'] as String,
      skillId: json['skill_id'] as String,
      proficiencyLevel: json['proficiency_level'] as String?,
      isVerified: json['is_verified'] as bool? ?? false,
      verifiedAt: json['verified_at'] != null
          ? DateTime.parse(json['verified_at'] as String)
          : null,
      verifiedBy: json['verified_by'] as String?,
      createdAt: DateTime.parse(json['created_at'] as String),
    );
  }

  /// Creates insert data for linking a doer to a skill.
  ///
  /// @param doerId The doer's UUID.
  /// @param skillId The skill's UUID.
  /// @param proficiencyLevel Optional proficiency level.
  /// @returns A map suitable for Supabase insert.
  static Map<String, dynamic> createInsertData({
    required String doerId,
    required String skillId,
    String? proficiencyLevel,
  }) {
    return {
      'doer_id': doerId,
      'skill_id': skillId,
      if (proficiencyLevel != null) 'proficiency_level': proficiencyLevel,
    };
  }
}

/// Junction model for the `doer_subjects` table.
///
/// Links doers to subjects they specialize in, with a flag for their
/// primary area of expertise.
///
/// ## JSON Structure
///
/// ```json
/// {
///   "id": "junction-uuid",
///   "doer_id": "doer-uuid",
///   "subject_id": "subject-uuid",
///   "is_primary": true,
///   "created_at": "2024-01-01T00:00:00Z"
/// }
/// ```
///
/// ## See Also
///
/// - [DoerModel] for the doer side of the relationship
/// - [SubjectModel] for the subject side of the relationship
class DoerSubjectModel {
  /// Unique identifier for this junction record.
  final String id;

  /// Reference to the doer.
  ///
  /// Foreign key to `doers.id`.
  final String doerId;

  /// Reference to the subject.
  ///
  /// Foreign key to `subjects.id`.
  final String subjectId;

  /// Whether this is the doer's primary subject.
  ///
  /// Only one subject should be marked as primary per doer.
  /// Used for project matching and profile display.
  final bool isPrimary;

  /// Timestamp when this subject was added to the doer's profile.
  final DateTime createdAt;

  /// Creates a new [DoerSubjectModel] with the specified values.
  const DoerSubjectModel({
    required this.id,
    required this.doerId,
    required this.subjectId,
    this.isPrimary = false,
    required this.createdAt,
  });

  /// Creates a [DoerSubjectModel] from a JSON map.
  ///
  /// @param json The JSON map from the database response.
  /// @returns A new [DoerSubjectModel] instance.
  factory DoerSubjectModel.fromJson(Map<String, dynamic> json) {
    return DoerSubjectModel(
      id: json['id'] as String,
      doerId: json['doer_id'] as String,
      subjectId: json['subject_id'] as String,
      isPrimary: json['is_primary'] as bool? ?? false,
      createdAt: DateTime.parse(json['created_at'] as String),
    );
  }

  /// Creates insert data for linking a doer to a subject.
  ///
  /// @param doerId The doer's UUID.
  /// @param subjectId The subject's UUID.
  /// @param isPrimary Whether this is the primary subject.
  /// @returns A map suitable for Supabase insert.
  static Map<String, dynamic> createInsertData({
    required String doerId,
    required String subjectId,
    bool isPrimary = false,
  }) {
    return {
      'doer_id': doerId,
      'subject_id': subjectId,
      'is_primary': isPrimary,
    };
  }
}
