// Copyright 2024 Doer App. All rights reserved.
// Use of this source code is governed by a BSD-style license.

/// Project models for the Doer application.
///
/// This file contains models related to projects (tasks/assignments) that
/// doers work on, including project details, status tracking, and related
/// statistics and reviews.
///
/// ## Project Lifecycle
///
/// ```
/// OPEN
///   │ (supervisor creates project)
///   ▼
/// ASSIGNED
///   │ (doer accepts project)
///   ▼
/// IN_PROGRESS
///   │ (doer works on project)
///   ▼
/// SUBMITTED
///   │ (doer submits work)
///   ▼
/// UNDER_REVIEW
///   │ (supervisor reviews)
///   ├────────────────────────┐
///   ▼                        ▼
/// COMPLETED              REVISION_REQUESTED
///   │                        │
///   ▼                        └──> IN_PROGRESS (cycle)
/// PAID
/// ```
///
/// ## Models in this file
///
/// - [ProjectModel] - Main project/task model
/// - [ProjectStatus] - Enum for project status values
/// - [ProjectUrgency] - Enum for urgency levels
/// - [DoerStats] - Aggregated doer performance statistics
/// - [ReviewModel] - Project reviews and ratings
library project_model;

/// Project model representing a task/assignment in the Doer application.
///
/// Projects are the core work units that doers complete. Each project has
/// a title, description, deadline, price, and goes through various status
/// stages from creation to completion.
///
/// ## JSON Structure
///
/// ```json
/// {
///   "id": "project-uuid",
///   "title": "Essay on Climate Change",
///   "description": "Write a 2000-word essay on climate change impacts",
///   "subject": "Environmental Science",
///   "status": "in_progress",
///   "urgency": "high",
///   "price": 500.00,
///   "deadline": "2024-01-20T23:59:59Z",
///   "created_at": "2024-01-15T10:00:00Z",
///   "accepted_at": "2024-01-15T12:00:00Z",
///   "supervisor_id": "supervisor-uuid",
///   "supervisor_name": "Dr. Smith",
///   "doer_id": "doer-uuid",
///   "word_count": 2000,
///   "reference_style": "APA",
///   "requirements": ["Original content", "Plagiarism-free"],
///   "has_revision": false
/// }
/// ```
///
/// ## Usage
///
/// ```dart
/// // Parse from database
/// final project = ProjectModel.fromJson(jsonData);
///
/// // Check project state
/// if (project.isOverdue) {
///   showOverdueWarning();
/// }
///
/// if (project.isUrgent) {
///   highlightAsUrgent();
/// }
///
/// // Display formatted price
/// Text(project.formattedPrice); // "Rs500"
/// ```
///
/// ## See Also
///
/// - [ProjectStatus] for project lifecycle stages
/// - [ProjectUrgency] for urgency levels
/// - [ReviewModel] for project reviews
class ProjectModel {
  /// Unique identifier for the project.
  ///
  /// UUID generated by the database.
  final String id;

  /// Title of the project.
  ///
  /// Brief, descriptive name shown in listings and headers.
  final String title;

  /// Detailed description of the project requirements.
  ///
  /// May include specific instructions, formatting requirements, etc.
  final String? description;

  /// Academic subject area of the project.
  ///
  /// Examples: `'Computer Science'`, `'English Literature'`, `'Mathematics'`.
  final String subject;

  /// Current status of the project.
  ///
  /// See [ProjectStatus] for possible values and lifecycle.
  final ProjectStatus status;

  /// Urgency level of the project.
  ///
  /// Affects visibility and may influence pricing.
  /// See [ProjectUrgency] for possible values.
  final ProjectUrgency urgency;

  /// Payment amount for the project in INR.
  ///
  /// The amount the doer will receive upon successful completion.
  final double price;

  /// Deadline for project submission.
  ///
  /// The date and time by which the doer must submit their work.
  final DateTime deadline;

  /// Timestamp when the project was created.
  ///
  /// Set by the database when a supervisor creates the project.
  final DateTime createdAt;

  /// Timestamp when a doer accepted the project.
  ///
  /// `null` if project has not been accepted yet.
  final DateTime? acceptedAt;

  /// Timestamp when the doer submitted their work.
  ///
  /// `null` if work has not been submitted yet.
  final DateTime? submittedAt;

  /// Timestamp when the project was marked as completed.
  ///
  /// `null` if not yet completed.
  final DateTime? completedAt;

  /// ID of the supervisor who created/manages this project.
  ///
  /// Foreign key to `profiles.id` where `user_type = 'supervisor'`.
  final String? supervisorId;

  /// Display name of the supervisor.
  ///
  /// Denormalized for convenience in UI display.
  final String? supervisorName;

  /// ID of the doer assigned to this project.
  ///
  /// Foreign key to `doers.id`. `null` if not yet assigned.
  final String? doerId;

  /// Required word count for the project.
  ///
  /// Used for essay-type projects. `null` if not applicable.
  final int? wordCount;

  /// Citation/reference style required.
  ///
  /// Examples: `'APA'`, `'MLA'`, `'Chicago'`, `'Harvard'`.
  /// `null` if no specific style required.
  final String? referenceStyle;

  /// List of specific requirements for the project.
  ///
  /// Examples: `['Plagiarism-free', 'Include citations', 'Original research']`.
  final List<String> requirements;

  /// Whether this project has had a revision requested.
  ///
  /// `true` if the supervisor has requested changes to submitted work.
  final bool hasRevision;

  /// Notes from supervisor for revision.
  ///
  /// Explains what changes are needed. `null` if no revision requested.
  final String? revisionNote;

  /// Creates a new [ProjectModel] with the specified values.
  ///
  /// Required parameters:
  /// - [id]: Unique project identifier
  /// - [title]: Project title
  /// - [subject]: Academic subject
  /// - [status]: Current status
  /// - [urgency]: Urgency level
  /// - [price]: Payment amount
  /// - [deadline]: Submission deadline
  /// - [createdAt]: Creation timestamp
  const ProjectModel({
    required this.id,
    required this.title,
    this.description,
    required this.subject,
    required this.status,
    required this.urgency,
    required this.price,
    required this.deadline,
    required this.createdAt,
    this.acceptedAt,
    this.submittedAt,
    this.completedAt,
    this.supervisorId,
    this.supervisorName,
    this.doerId,
    this.wordCount,
    this.referenceStyle,
    this.requirements = const [],
    this.hasRevision = false,
    this.revisionNote,
  });

  /// Creates a [ProjectModel] from a JSON map (database response).
  ///
  /// @param json The JSON map from the database response.
  /// @returns A new [ProjectModel] instance.
  factory ProjectModel.fromJson(Map<String, dynamic> json) {
    return ProjectModel(
      id: json['id'] as String,
      title: json['title'] as String,
      description: json['description'] as String?,
      subject: json['subject'] as String? ?? 'General',
      status: ProjectStatus.fromString(json['status'] as String? ?? 'open'),
      urgency: ProjectUrgency.fromString(json['urgency'] as String? ?? 'normal'),
      price: (json['price'] as num?)?.toDouble() ?? 0.0,
      deadline: DateTime.parse(json['deadline'] as String),
      createdAt: DateTime.parse(json['created_at'] as String),
      acceptedAt: json['accepted_at'] != null
          ? DateTime.parse(json['accepted_at'] as String)
          : null,
      submittedAt: json['submitted_at'] != null
          ? DateTime.parse(json['submitted_at'] as String)
          : null,
      completedAt: json['completed_at'] != null
          ? DateTime.parse(json['completed_at'] as String)
          : null,
      supervisorId: json['supervisor_id'] as String?,
      supervisorName: json['supervisor_name'] as String?,
      doerId: json['doer_id'] as String?,
      wordCount: json['word_count'] as int?,
      referenceStyle: json['reference_style'] as String?,
      requirements: (json['requirements'] as List<dynamic>?)?.cast<String>() ?? [],
      hasRevision: json['has_revision'] as bool? ?? false,
      revisionNote: json['revision_note'] as String?,
    );
  }

  /// Converts this [ProjectModel] to a JSON map.
  ///
  /// @returns A map of column names to values.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'description': description,
      'subject': subject,
      'status': status.value,
      'urgency': urgency.value,
      'price': price,
      'deadline': deadline.toIso8601String(),
      'created_at': createdAt.toIso8601String(),
      'accepted_at': acceptedAt?.toIso8601String(),
      'submitted_at': submittedAt?.toIso8601String(),
      'completed_at': completedAt?.toIso8601String(),
      'supervisor_id': supervisorId,
      'supervisor_name': supervisorName,
      'doer_id': doerId,
      'word_count': wordCount,
      'reference_style': referenceStyle,
      'requirements': requirements,
      'has_revision': hasRevision,
      'revision_note': revisionNote,
    };
  }

  /// Creates a copy of this [ProjectModel] with updated fields.
  ///
  /// @returns A new [ProjectModel] instance with the specified changes.
  ProjectModel copyWith({
    String? id,
    String? title,
    String? description,
    String? subject,
    ProjectStatus? status,
    ProjectUrgency? urgency,
    double? price,
    DateTime? deadline,
    DateTime? createdAt,
    DateTime? acceptedAt,
    DateTime? submittedAt,
    DateTime? completedAt,
    String? supervisorId,
    String? supervisorName,
    String? doerId,
    int? wordCount,
    String? referenceStyle,
    List<String>? requirements,
    bool? hasRevision,
    String? revisionNote,
  }) {
    return ProjectModel(
      id: id ?? this.id,
      title: title ?? this.title,
      description: description ?? this.description,
      subject: subject ?? this.subject,
      status: status ?? this.status,
      urgency: urgency ?? this.urgency,
      price: price ?? this.price,
      deadline: deadline ?? this.deadline,
      createdAt: createdAt ?? this.createdAt,
      acceptedAt: acceptedAt ?? this.acceptedAt,
      submittedAt: submittedAt ?? this.submittedAt,
      completedAt: completedAt ?? this.completedAt,
      supervisorId: supervisorId ?? this.supervisorId,
      supervisorName: supervisorName ?? this.supervisorName,
      doerId: doerId ?? this.doerId,
      wordCount: wordCount ?? this.wordCount,
      referenceStyle: referenceStyle ?? this.referenceStyle,
      requirements: requirements ?? this.requirements,
      hasRevision: hasRevision ?? this.hasRevision,
      revisionNote: revisionNote ?? this.revisionNote,
    );
  }

  /// Checks if the project is urgent based on time remaining.
  ///
  /// Returns `true` if less than 6 hours remain until deadline
  /// and the deadline has not passed.
  ///
  /// @returns `true` if project should be highlighted as urgent.
  bool get isUrgent {
    final remaining = deadline.difference(DateTime.now());
    return remaining.inHours < 6 && remaining.isNegative == false;
  }

  /// Gets the time remaining until the deadline.
  ///
  /// Returns a [Duration] which may be negative if the deadline has passed.
  ///
  /// @returns Duration until deadline.
  Duration get timeRemaining => deadline.difference(DateTime.now());

  /// Checks if the deadline has passed.
  ///
  /// @returns `true` if current time is after the deadline.
  bool get isOverdue => DateTime.now().isAfter(deadline);

  /// Gets the formatted price string with currency symbol.
  ///
  /// Returns the price in INR format without decimal places.
  ///
  /// @returns Formatted string like `"Rs500"`.
  String get formattedPrice => '\u20B9${price.toStringAsFixed(0)}';
}

// =============================================================================
// Project Status Enum
// =============================================================================

/// Enumeration of project status values.
///
/// Represents the lifecycle stages a project goes through from creation
/// to payment completion.
///
/// ## Status Flow
///
/// ```
/// open -> assigned -> in_progress -> submitted -> under_review
///                                                      |
///                         +----------------------------+
///                         |                            |
///                         v                            v
///                   revision_requested           completed -> paid
///                         |
///                         v
///                    in_progress (cycle back)
/// ```
///
/// ## Usage
///
/// ```dart
/// final status = ProjectStatus.fromString('in_progress');
/// print(status.displayName); // "In Progress"
///
/// // Use in switch
/// switch (project.status) {
///   case ProjectStatus.open:
///     showAcceptButton();
///   case ProjectStatus.inProgress:
///     showWorkArea();
///   // ...
/// }
/// ```
enum ProjectStatus {
  /// Project is open for doers to accept.
  ///
  /// Initial state after supervisor creates a project.
  open('open'),

  /// Project has been assigned to a doer.
  ///
  /// Transition state before work begins.
  assigned('assigned'),

  /// Doer is actively working on the project.
  ///
  /// Main working state.
  inProgress('in_progress'),

  /// Doer has submitted their work.
  ///
  /// Awaiting supervisor review.
  submitted('submitted'),

  /// Supervisor is reviewing the submission.
  ///
  /// May transition to completed or revision_requested.
  underReview('under_review'),

  /// Supervisor has requested changes.
  ///
  /// Doer needs to make revisions and resubmit.
  revisionRequested('revision_requested'),

  /// Project has been completed and approved.
  ///
  /// Work is accepted, awaiting payment.
  completed('completed'),

  /// Payment has been processed for the project.
  ///
  /// Final state indicating successful completion.
  paid('paid'),

  /// Project has been cancelled.
  ///
  /// Terminal state - no further actions possible.
  cancelled('cancelled');

  /// The database value for this status.
  final String value;

  /// Creates a [ProjectStatus] with the given database value.
  const ProjectStatus(this.value);

  /// Creates a [ProjectStatus] from a database string value.
  ///
  /// Returns [ProjectStatus.open] if the value doesn't match any status.
  ///
  /// @param value The status string from the database.
  /// @returns The matching [ProjectStatus] enum value.
  static ProjectStatus fromString(String value) {
    return ProjectStatus.values.firstWhere(
      (e) => e.value == value,
      orElse: () => ProjectStatus.open,
    );
  }

  /// Gets a human-readable display name for this status.
  ///
  /// @returns Formatted status name for UI display.
  String get displayName {
    switch (this) {
      case ProjectStatus.open:
        return 'Open';
      case ProjectStatus.assigned:
        return 'Assigned';
      case ProjectStatus.inProgress:
        return 'In Progress';
      case ProjectStatus.submitted:
        return 'Submitted';
      case ProjectStatus.underReview:
        return 'Under Review';
      case ProjectStatus.revisionRequested:
        return 'Revision Requested';
      case ProjectStatus.completed:
        return 'Completed';
      case ProjectStatus.paid:
        return 'Paid';
      case ProjectStatus.cancelled:
        return 'Cancelled';
    }
  }
}

// =============================================================================
// Project Urgency Enum
// =============================================================================

/// Enumeration of project urgency levels.
///
/// Indicates how time-sensitive a project is, which may affect
/// pricing, visibility, and doer matching.
///
/// ## Usage
///
/// ```dart
/// final urgency = ProjectUrgency.fromString('high');
///
/// // Use for styling
/// Color getUrgencyColor(ProjectUrgency urgency) {
///   switch (urgency) {
///     case ProjectUrgency.low: return Colors.green;
///     case ProjectUrgency.normal: return Colors.blue;
///     case ProjectUrgency.high: return Colors.orange;
///     case ProjectUrgency.urgent: return Colors.red;
///   }
/// }
/// ```
enum ProjectUrgency {
  /// Low urgency - flexible deadline.
  ///
  /// No rush, doer can take their time.
  low('low'),

  /// Normal urgency - standard timeline.
  ///
  /// Default urgency level.
  normal('normal'),

  /// High urgency - sooner deadline preferred.
  ///
  /// Project should be prioritized.
  high('high'),

  /// Urgent - needs immediate attention.
  ///
  /// Highest priority, may include premium pricing.
  urgent('urgent');

  /// The database value for this urgency level.
  final String value;

  /// Creates a [ProjectUrgency] with the given database value.
  const ProjectUrgency(this.value);

  /// Creates a [ProjectUrgency] from a database string value.
  ///
  /// Returns [ProjectUrgency.normal] if the value doesn't match.
  ///
  /// @param value The urgency string from the database.
  /// @returns The matching [ProjectUrgency] enum value.
  static ProjectUrgency fromString(String value) {
    return ProjectUrgency.values.firstWhere(
      (e) => e.value == value,
      orElse: () => ProjectUrgency.normal,
    );
  }
}

// =============================================================================
// Doer Statistics Model
// =============================================================================

/// Aggregated statistics for a doer's performance.
///
/// Used for dashboard displays and performance tracking.
/// These values are typically calculated from aggregate queries
/// or maintained as denormalized data.
///
/// ## JSON Structure
///
/// ```json
/// {
///   "active_projects": 3,
///   "completed_projects": 25,
///   "total_earnings": 50000.00,
///   "rating": 4.8,
///   "success_rate": 96.5,
///   "on_time_delivery_rate": 92.0
/// }
/// ```
///
/// ## Usage
///
/// ```dart
/// final stats = DoerStats.fromJson(data);
///
/// // Display in dashboard
/// Text('Projects Completed: ${stats.completedProjects}');
/// Text('Total Earned: ${stats.formattedEarnings}');
/// Text('Rating: ${stats.rating.toStringAsFixed(1)} stars');
/// ```
class DoerStats {
  /// Number of projects currently in progress.
  ///
  /// Projects with status in_progress, submitted, or under_review.
  final int activeProjects;

  /// Total number of completed projects.
  ///
  /// Projects with status completed or paid.
  final int completedProjects;

  /// Total earnings in INR.
  ///
  /// Sum of payments for all completed projects.
  final double totalEarnings;

  /// Average rating from reviews (0.0 to 5.0).
  ///
  /// Mean of all review ratings received.
  final double rating;

  /// Percentage of projects completed successfully.
  ///
  /// Calculated as: (completed / total accepted) * 100.
  final double successRate;

  /// Percentage of projects delivered on time.
  ///
  /// Calculated as: (on-time / total completed) * 100.
  final double onTimeDeliveryRate;

  /// Creates a new [DoerStats] with the specified values.
  ///
  /// All parameters have default values of 0 or 0.0.
  const DoerStats({
    this.activeProjects = 0,
    this.completedProjects = 0,
    this.totalEarnings = 0.0,
    this.rating = 0.0,
    this.successRate = 0.0,
    this.onTimeDeliveryRate = 0.0,
  });

  /// Creates a [DoerStats] from a JSON map.
  ///
  /// @param json The JSON map containing statistics.
  /// @returns A new [DoerStats] instance.
  factory DoerStats.fromJson(Map<String, dynamic> json) {
    return DoerStats(
      activeProjects: json['active_projects'] as int? ?? 0,
      completedProjects: json['completed_projects'] as int? ?? 0,
      totalEarnings: (json['total_earnings'] as num?)?.toDouble() ?? 0.0,
      rating: (json['rating'] as num?)?.toDouble() ?? 0.0,
      successRate: (json['success_rate'] as num?)?.toDouble() ?? 0.0,
      onTimeDeliveryRate: (json['on_time_delivery_rate'] as num?)?.toDouble() ?? 0.0,
    );
  }

  /// Gets formatted earnings string with currency symbol.
  ///
  /// @returns Formatted string like `"Rs50,000"`.
  String get formattedEarnings => '\u20B9${totalEarnings.toStringAsFixed(0)}';
}

// =============================================================================
// Review Model
// =============================================================================

/// Model for project reviews submitted by supervisors.
///
/// Reviews are submitted after a project is completed and include
/// a rating and optional comment.
///
/// ## JSON Structure
///
/// ```json
/// {
///   "id": "review-uuid",
///   "project_id": "project-uuid",
///   "project_title": "Essay on Climate Change",
///   "reviewer_name": "Dr. Smith",
///   "rating": 4.5,
///   "comment": "Excellent work, well researched.",
///   "created_at": "2024-01-20T14:00:00Z"
/// }
/// ```
///
/// ## Usage
///
/// ```dart
/// final review = ReviewModel.fromJson(data);
///
/// // Display review
/// Row(children: [
///   StarRating(value: review.rating),
///   Text('by ${review.reviewerName}'),
/// ]);
/// if (review.comment != null) {
///   Text(review.comment!);
/// }
/// ```
class ReviewModel {
  /// Unique identifier for the review.
  final String id;

  /// Reference to the project being reviewed.
  ///
  /// Foreign key to `projects.id`.
  final String projectId;

  /// Title of the project (denormalized).
  ///
  /// Stored for display convenience.
  final String projectTitle;

  /// Name of the reviewer.
  ///
  /// Typically the supervisor's name. Defaults to 'Anonymous'.
  final String reviewerName;

  /// Rating given (0.0 to 5.0).
  ///
  /// Typically displayed as stars.
  final double rating;

  /// Optional comment explaining the rating.
  ///
  /// `null` if no comment was provided.
  final String? comment;

  /// Timestamp when the review was created.
  final DateTime createdAt;

  /// Creates a new [ReviewModel] with the specified values.
  const ReviewModel({
    required this.id,
    required this.projectId,
    required this.projectTitle,
    this.reviewerName = 'Anonymous',
    required this.rating,
    this.comment,
    required this.createdAt,
  });

  /// Creates a [ReviewModel] from a JSON map.
  ///
  /// @param json The JSON map from the database response.
  /// @returns A new [ReviewModel] instance.
  factory ReviewModel.fromJson(Map<String, dynamic> json) {
    return ReviewModel(
      id: json['id'] as String,
      projectId: json['project_id'] as String,
      projectTitle: json['project_title'] as String? ?? 'Project',
      reviewerName: json['reviewer_name'] as String? ?? 'Anonymous',
      rating: (json['rating'] as num).toDouble(),
      comment: json['comment'] as String?,
      createdAt: DateTime.parse(json['created_at'] as String),
    );
  }
}
