// Copyright 2024 Doer App. All rights reserved.
// Use of this source code is governed by a BSD-style license.

/// Quiz models for the Doer application.
///
/// This file contains models related to the activation quiz that doers
/// must pass as part of the activation process. The quiz tests understanding
/// of platform policies, work quality standards, and best practices.
///
/// ## Quiz Flow
///
/// ```
/// 1. Fetch Quiz Questions
///    │
///    └── GET quiz_questions WHERE is_active = true ORDER BY order_index
///    │
/// 2. User Takes Quiz
///    │
///    └── User selects answer option for each question
///    │
/// 3. Submit Quiz Attempt
///    │
///    ├── Calculate score based on correct answers
///    ├── Create quiz_attempt record
///    └── Store quiz_answers for each question
///    │
/// 4. Check Result
///    │
///    ├── Score >= 80%: PASS -> Update activation status
///    └── Score < 80%: FAIL -> Allow retry
/// ```
///
/// ## Models in this file
///
/// - [QuizQuestion] - A quiz question with options
/// - [QuizOption] - An answer option for a question
/// - [QuizAttempt] - Record of a quiz attempt with score
/// - [QuizAnswer] - Individual answer within an attempt
/// - [QuizStatus] - Enum for quiz completion status
library quiz_model;

/// Quiz question model representing a question in the activation quiz.
///
/// Each question has a text prompt, multiple choice options, and a correct
/// answer indicated by index. Optional explanation provides feedback.
///
/// ## JSON Structure
///
/// ```json
/// {
///   "id": "question-uuid",
///   "question": "What should you do if you cannot meet a deadline?",
///   "options": [
///     { "id": "opt-1", "text": "Ignore it" },
///     { "id": "opt-2", "text": "Inform the supervisor immediately" },
///     { "id": "opt-3", "text": "Submit incomplete work" },
///     { "id": "opt-4", "text": "Wait until the last moment" }
///   ],
///   "correct_option_index": 1,
///   "explanation": "Early communication allows for problem-solving.",
///   "order_index": 1
/// }
/// ```
///
/// ## Usage
///
/// ```dart
/// // Parse questions from database
/// final questions = data.map((q) => QuizQuestion.fromJson(q)).toList();
///
/// // Check if user's answer is correct
/// final isCorrect = question.isCorrect(selectedIndex);
///
/// // Get correct answer for feedback
/// final correctOption = question.options[question.correctOptionIndex];
/// ```
///
/// ## See Also
///
/// - [QuizOption] for answer options
/// - [QuizAttempt] for tracking quiz attempts
class QuizQuestion {
  /// Unique identifier for the question.
  ///
  /// UUID generated by the database.
  final String id;

  /// The question text/prompt to display.
  ///
  /// Should be clear, unambiguous, and test understanding
  /// of platform policies or best practices.
  final String question;

  /// List of answer options for this question.
  ///
  /// Typically 2-5 options. One option should be correct,
  /// indicated by [correctOptionIndex].
  final List<QuizOption> options;

  /// Index of the correct option in the [options] list.
  ///
  /// Zero-based index. Must be a valid index for [options].
  final int correctOptionIndex;

  /// Explanation shown after answering.
  ///
  /// Helps the user understand why an answer is correct.
  /// Especially useful for learning from wrong answers.
  final String? explanation;

  /// Display order within the quiz.
  ///
  /// Questions are sorted by this value. Lower numbers appear first.
  final int orderIndex;

  /// Creates a new [QuizQuestion] with the specified values.
  ///
  /// Required parameters:
  /// - [id]: Unique question identifier
  /// - [question]: The question text
  /// - [options]: List of answer options
  /// - [correctOptionIndex]: Index of the correct answer
  /// - [orderIndex]: Display order position
  const QuizQuestion({
    required this.id,
    required this.question,
    required this.options,
    required this.correctOptionIndex,
    this.explanation,
    required this.orderIndex,
  });

  /// Creates a [QuizQuestion] from a JSON map (database response).
  ///
  /// Parses the question data and nested options list.
  ///
  /// @param json The JSON map from the database response.
  /// @returns A new [QuizQuestion] instance.
  ///
  /// @throws FormatException if required fields are missing.
  factory QuizQuestion.fromJson(Map<String, dynamic> json) {
    final optionsList = (json['options'] as List<dynamic>?)
            ?.map((e) => QuizOption.fromJson(e as Map<String, dynamic>))
            .toList() ??
        [];

    return QuizQuestion(
      id: json['id'] as String,
      question: json['question'] as String,
      options: optionsList,
      correctOptionIndex: json['correct_option_index'] as int? ?? 0,
      explanation: json['explanation'] as String?,
      orderIndex: json['order_index'] as int? ?? 0,
    );
  }

  /// Converts this [QuizQuestion] to a JSON map.
  ///
  /// @returns A map of column names to values.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'question': question,
      'options': options.map((e) => e.toJson()).toList(),
      'correct_option_index': correctOptionIndex,
      'explanation': explanation,
      'order_index': orderIndex,
    };
  }

  /// Checks if the selected option index is the correct answer.
  ///
  /// @param selectedIndex The index of the option the user selected.
  /// @returns `true` if the selected index matches [correctOptionIndex].
  ///
  /// ## Example
  ///
  /// ```dart
  /// if (question.isCorrect(userSelection)) {
  ///   score++;
  ///   showCorrectFeedback();
  /// } else {
  ///   showIncorrectFeedback(question.explanation);
  /// }
  /// ```
  bool isCorrect(int selectedIndex) => selectedIndex == correctOptionIndex;
}

// =============================================================================
// Quiz Option Model
// =============================================================================

/// Quiz option model representing an answer option for a question.
///
/// Each option has an ID and display text. The correct option is
/// indicated by the parent [QuizQuestion.correctOptionIndex].
///
/// ## JSON Structure
///
/// ```json
/// {
///   "id": "option-uuid",
///   "text": "Inform the supervisor immediately"
/// }
/// ```
class QuizOption {
  /// Unique identifier for the option.
  ///
  /// Used for tracking and analytics.
  final String id;

  /// The option text to display.
  ///
  /// Should be clear and distinct from other options.
  final String text;

  /// Creates a new [QuizOption] with the specified values.
  ///
  /// Required parameters:
  /// - [id]: Unique option identifier
  /// - [text]: The option display text
  const QuizOption({
    required this.id,
    required this.text,
  });

  /// Creates a [QuizOption] from a JSON map.
  ///
  /// @param json The JSON map containing option data.
  /// @returns A new [QuizOption] instance.
  factory QuizOption.fromJson(Map<String, dynamic> json) {
    return QuizOption(
      id: json['id'] as String? ?? '',
      text: json['text'] as String,
    );
  }

  /// Converts this [QuizOption] to a JSON map.
  ///
  /// @returns A map of column names to values.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'text': text,
    };
  }
}

// =============================================================================
// Quiz Attempt Model
// =============================================================================

/// Quiz attempt model representing a doer's quiz attempt.
///
/// Records the attempt details including score, pass/fail status,
/// attempt number, and individual answers.
///
/// ## JSON Structure
///
/// ```json
/// {
///   "id": "attempt-uuid",
///   "doer_id": "doer-uuid",
///   "score": 8,
///   "total_questions": 10,
///   "passed": true,
///   "attempt_number": 1,
///   "answers": [
///     { "question_id": "q1", "selected_option_index": 1, "is_correct": true }
///   ],
///   "attempted_at": "2024-01-15T10:25:00Z"
/// }
/// ```
///
/// ## Usage
///
/// ```dart
/// // Check if attempt passed
/// if (attempt.passed) {
///   showSuccessScreen();
///   updateActivationStatus();
/// } else {
///   showRetryOption();
/// }
///
/// // Display results
/// Text('Score: ${attempt.percentage.toStringAsFixed(0)}%');
/// Text('Correct: ${attempt.score}/${attempt.totalQuestions}');
/// ```
///
/// ## See Also
///
/// - [QuizAnswer] for individual answers
/// - [ActivationStatus] for tracking quiz completion
class QuizAttempt {
  /// Unique identifier for this attempt.
  ///
  /// UUID generated by the database.
  final String id;

  /// Reference to the doer who made this attempt.
  ///
  /// Foreign key to `doers.id`.
  final String doerId;

  /// Number of questions answered correctly.
  ///
  /// Integer count of correct answers.
  final int score;

  /// Total number of questions in this attempt.
  ///
  /// Used to calculate percentage.
  final int totalQuestions;

  /// Whether the doer passed the quiz.
  ///
  /// Passing threshold is typically 80% (8/10).
  final bool passed;

  /// Which attempt this is for the doer.
  ///
  /// First attempt = 1, second = 2, etc.
  /// Used to track retry patterns.
  final int attemptNumber;

  /// List of individual answers for each question.
  ///
  /// Contains the selected option and correctness for each question.
  final List<QuizAnswer> answers;

  /// Timestamp when the quiz was completed.
  ///
  /// Set when the user submits their answers.
  final DateTime attemptedAt;

  /// Creates a new [QuizAttempt] with the specified values.
  ///
  /// Required parameters:
  /// - [id]: Unique attempt identifier
  /// - [doerId]: Reference to the doer
  /// - [score]: Number of correct answers
  /// - [totalQuestions]: Total questions in the quiz
  /// - [passed]: Whether the attempt passed
  /// - [attemptNumber]: Which attempt this is
  /// - [attemptedAt]: When the attempt was made
  const QuizAttempt({
    required this.id,
    required this.doerId,
    required this.score,
    required this.totalQuestions,
    required this.passed,
    required this.attemptNumber,
    this.answers = const [],
    required this.attemptedAt,
  });

  /// Creates a [QuizAttempt] from a JSON map (database response).
  ///
  /// @param json The JSON map from the database response.
  /// @returns A new [QuizAttempt] instance.
  factory QuizAttempt.fromJson(Map<String, dynamic> json) {
    final answersList = (json['answers'] as List<dynamic>?)
            ?.map((e) => QuizAnswer.fromJson(e as Map<String, dynamic>))
            .toList() ??
        [];

    return QuizAttempt(
      id: json['id'] as String,
      doerId: json['doer_id'] as String,
      score: json['score'] as int,
      totalQuestions: json['total_questions'] as int,
      passed: json['passed'] as bool,
      attemptNumber: json['attempt_number'] as int? ?? 1,
      answers: answersList,
      attemptedAt: DateTime.parse(json['attempted_at'] as String),
    );
  }

  /// Converts this [QuizAttempt] to a JSON map.
  ///
  /// @returns A map of column names to values.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'doer_id': doerId,
      'score': score,
      'total_questions': totalQuestions,
      'passed': passed,
      'attempt_number': attemptNumber,
      'answers': answers.map((e) => e.toJson()).toList(),
      'attempted_at': attemptedAt.toIso8601String(),
    };
  }

  /// Gets the score as a percentage (0.0 to 100.0).
  ///
  /// Calculated as: (score / totalQuestions) * 100.
  ///
  /// @returns Percentage score as a double.
  ///
  /// ## Example
  ///
  /// ```dart
  /// Text('${attempt.percentage.toStringAsFixed(0)}%'); // "80%"
  /// CircularProgressIndicator(value: attempt.percentage / 100);
  /// ```
  double get percentage => (score / totalQuestions) * 100;
}

// =============================================================================
// Quiz Answer Model
// =============================================================================

/// Quiz answer model representing a single answer within an attempt.
///
/// Records which option was selected for a question and whether it was correct.
///
/// ## JSON Structure
///
/// ```json
/// {
///   "question_id": "question-uuid",
///   "selected_option_index": 1,
///   "is_correct": true
/// }
/// ```
class QuizAnswer {
  /// Reference to the question being answered.
  ///
  /// Foreign key to `quiz_questions.id`.
  final String questionId;

  /// Index of the option the user selected.
  ///
  /// Zero-based index into the question's options list.
  final int selectedOptionIndex;

  /// Whether the selected option was correct.
  ///
  /// `true` if selectedOptionIndex matches the question's correctOptionIndex.
  final bool isCorrect;

  /// Creates a new [QuizAnswer] with the specified values.
  ///
  /// Required parameters:
  /// - [questionId]: Reference to the question
  /// - [selectedOptionIndex]: Index of selected option
  /// - [isCorrect]: Whether the answer was correct
  const QuizAnswer({
    required this.questionId,
    required this.selectedOptionIndex,
    required this.isCorrect,
  });

  /// Creates a [QuizAnswer] from a JSON map.
  ///
  /// @param json The JSON map from the database response.
  /// @returns A new [QuizAnswer] instance.
  factory QuizAnswer.fromJson(Map<String, dynamic> json) {
    return QuizAnswer(
      questionId: json['question_id'] as String,
      selectedOptionIndex: json['selected_option_index'] as int,
      isCorrect: json['is_correct'] as bool,
    );
  }

  /// Converts this [QuizAnswer] to a JSON map.
  ///
  /// @returns A map of column names to values.
  Map<String, dynamic> toJson() {
    return {
      'question_id': questionId,
      'selected_option_index': selectedOptionIndex,
      'is_correct': isCorrect,
    };
  }
}

// =============================================================================
// Quiz Status Enum
// =============================================================================

/// Enumeration of quiz completion status values.
///
/// Represents the doer's current state with respect to the activation quiz.
///
/// ## Usage
///
/// ```dart
/// switch (quizStatus) {
///   case QuizStatus.notAttempted:
///     showStartQuizButton();
///   case QuizStatus.inProgress:
///     showContinueButton();
///   case QuizStatus.passed:
///     showSuccessBadge();
///   case QuizStatus.failed:
///     showRetryButton();
/// }
/// ```
enum QuizStatus {
  /// The doer has not attempted the quiz yet.
  ///
  /// Initial state before first attempt.
  notAttempted,

  /// The doer is currently taking the quiz.
  ///
  /// Quiz has been started but not yet submitted.
  inProgress,

  /// The doer has passed the quiz.
  ///
  /// Score was 80% or higher. Activation can proceed.
  passed,

  /// The doer has failed the quiz.
  ///
  /// Score was below 80%. Retry is allowed.
  failed,
}
