// Copyright 2024 Doer App. All rights reserved.
// Use of this source code is governed by a BSD-style license.

/// Training models for the Doer application.
///
/// This file contains models related to the training modules that doers
/// must complete as the first step of the activation process. Training
/// covers platform policies, work quality standards, and best practices.
///
/// ## Training Flow
///
/// ```
/// 1. Fetch Training Modules
///    │
///    └── GET training_modules WHERE is_active = true ORDER BY order_index
///    │
/// 2. User Views Module
///    │
///    ├── Create training_progress record if first time
///    └── Update progress as content is consumed
///    │
/// 3. Mark Module Complete
///    │
///    ├── Set is_completed = true
///    └── Set completed_at timestamp
///    │
/// 4. Check All Modules Complete
///    │
///    └── If all required modules complete -> Training step done
/// ```
///
/// ## Models in this file
///
/// - [TrainingModule] - Training content metadata (video, PDF, article)
/// - [TrainingModuleType] - Enum for content types
/// - [TrainingProgress] - Doer's progress through a module
library training_model;

/// Training module model representing training content.
///
/// Each module contains training material in the form of video, PDF,
/// or article content. Doers must complete all required modules
/// before proceeding to the quiz.
///
/// ## JSON Structure
///
/// ```json
/// {
///   "id": "module-uuid",
///   "title": "Platform Guidelines",
///   "description": "Learn about our quality standards and policies",
///   "type": "video",
///   "content_url": "https://storage.supabase.co/training/video1.mp4",
///   "duration_minutes": 15,
///   "order_index": 1,
///   "is_required": true,
///   "created_at": "2024-01-01T00:00:00Z"
/// }
/// ```
///
/// ## Usage
///
/// ```dart
/// // Parse modules from database
/// final modules = data.map((m) => TrainingModule.fromJson(m)).toList();
///
/// // Display module based on type
/// switch (module.type) {
///   case TrainingModuleType.video:
///     showVideoPlayer(module.contentUrl);
///   case TrainingModuleType.pdf:
///     showPdfViewer(module.contentUrl);
///   case TrainingModuleType.article:
///     showArticleReader(module.contentUrl);
/// }
///
/// // Show duration
/// Text('Duration: ${module.durationMinutes} min');
/// ```
///
/// ## See Also
///
/// - [TrainingModuleType] for content type options
/// - [TrainingProgress] for tracking completion
/// - [ActivationStatus] for overall activation progress
class TrainingModule {
  /// Unique identifier for the training module.
  ///
  /// UUID generated by the database.
  final String id;

  /// Display title of the training module.
  ///
  /// Shown in the module list and as header when viewing.
  final String title;

  /// Description of what the module covers.
  ///
  /// Brief overview of learning objectives.
  final String description;

  /// Type of content in this module.
  ///
  /// Determines which viewer/player to use.
  /// See [TrainingModuleType] for options.
  final TrainingModuleType type;

  /// URL to the training content.
  ///
  /// Points to video, PDF, or article content in storage.
  /// Must be accessible by the app (signed URL or public).
  final String contentUrl;

  /// Estimated duration to complete the module in minutes.
  ///
  /// Used for time estimates and progress calculation.
  final int durationMinutes;

  /// Display order in the module list.
  ///
  /// Modules are sorted by this value. Lower numbers appear first.
  final int orderIndex;

  /// Whether this module is required for activation.
  ///
  /// Required modules must be completed to proceed.
  /// Optional modules are for additional learning.
  final bool isRequired;

  /// Timestamp when the module was created.
  ///
  /// Set by the database on insert.
  final DateTime createdAt;

  /// Creates a new [TrainingModule] with the specified values.
  ///
  /// Required parameters:
  /// - [id]: Unique module identifier
  /// - [title]: Display title
  /// - [description]: Content description
  /// - [type]: Content type (video/PDF/article)
  /// - [contentUrl]: URL to the content
  /// - [durationMinutes]: Estimated duration
  /// - [orderIndex]: Display order
  /// - [createdAt]: Creation timestamp
  const TrainingModule({
    required this.id,
    required this.title,
    required this.description,
    required this.type,
    required this.contentUrl,
    required this.durationMinutes,
    required this.orderIndex,
    this.isRequired = true,
    required this.createdAt,
  });

  /// Creates a [TrainingModule] from a JSON map (database response).
  ///
  /// @param json The JSON map from the database response.
  /// @returns A new [TrainingModule] instance.
  ///
  /// @throws FormatException if required fields are missing.
  factory TrainingModule.fromJson(Map<String, dynamic> json) {
    return TrainingModule(
      id: json['id'] as String,
      title: json['title'] as String,
      description: json['description'] as String? ?? '',
      type: TrainingModuleType.fromString(json['type'] as String),
      contentUrl: json['content_url'] as String,
      durationMinutes: json['duration_minutes'] as int? ?? 0,
      orderIndex: json['order_index'] as int? ?? 0,
      isRequired: json['is_required'] as bool? ?? true,
      createdAt: DateTime.parse(json['created_at'] as String),
    );
  }

  /// Converts this [TrainingModule] to a JSON map.
  ///
  /// @returns A map of column names to values.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'description': description,
      'type': type.value,
      'content_url': contentUrl,
      'duration_minutes': durationMinutes,
      'order_index': orderIndex,
      'is_required': isRequired,
      'created_at': createdAt.toIso8601String(),
    };
  }
}

// =============================================================================
// Training Module Type Enum
// =============================================================================

/// Enumeration of training module content types.
///
/// Determines the format of training content and which viewer
/// component to use for display.
///
/// ## Usage
///
/// ```dart
/// // Parse from database
/// final type = TrainingModuleType.fromString(json['type']);
///
/// // Use appropriate viewer
/// Widget getViewer(TrainingModule module) {
///   switch (module.type) {
///     case TrainingModuleType.video:
///       return VideoPlayer(url: module.contentUrl);
///     case TrainingModuleType.pdf:
///       return PdfViewer(url: module.contentUrl);
///     case TrainingModuleType.article:
///       return ArticleReader(url: module.contentUrl);
///   }
/// }
///
/// // Get icon for type
/// IconData getIcon(TrainingModuleType type) {
///   switch (type) {
///     case TrainingModuleType.video: return Icons.play_circle;
///     case TrainingModuleType.pdf: return Icons.picture_as_pdf;
///     case TrainingModuleType.article: return Icons.article;
///   }
/// }
/// ```
enum TrainingModuleType {
  /// Video training content.
  ///
  /// Played in a video player. Typically MP4 format.
  /// Progress can be tracked by video position.
  video('video'),

  /// PDF document training content.
  ///
  /// Displayed in a PDF viewer.
  /// Progress can be tracked by pages viewed.
  pdf('pdf'),

  /// Article/text training content.
  ///
  /// Displayed in a text reader.
  /// May include HTML formatting.
  article('article');

  /// The database value for this content type.
  final String value;

  /// Creates a [TrainingModuleType] with the given database value.
  const TrainingModuleType(this.value);

  /// Creates a [TrainingModuleType] from a database string value.
  ///
  /// Returns [TrainingModuleType.video] if the value doesn't match.
  ///
  /// @param value The type string from the database.
  /// @returns The matching [TrainingModuleType] enum value.
  static TrainingModuleType fromString(String value) {
    return TrainingModuleType.values.firstWhere(
      (e) => e.value == value,
      orElse: () => TrainingModuleType.video,
    );
  }
}

// =============================================================================
// Training Progress Model
// =============================================================================

/// Training progress model tracking a doer's progress through a module.
///
/// Each progress record links a doer to a training module and tracks
/// how much of the content they have consumed.
///
/// ## JSON Structure
///
/// ```json
/// {
///   "id": "progress-uuid",
///   "doer_id": "doer-uuid",
///   "module_id": "module-uuid",
///   "is_completed": true,
///   "progress_percent": 100,
///   "completed_at": "2024-01-15T10:30:00Z",
///   "started_at": "2024-01-15T10:00:00Z"
/// }
/// ```
///
/// ## Usage
///
/// ```dart
/// // Check module completion
/// final progress = progressMap[module.id];
/// if (progress?.isCompleted ?? false) {
///   showCompletedBadge();
/// }
///
/// // Update progress as content is consumed
/// await updateProgress(progress.copyWith(
///   progressPercent: videoPosition.inSeconds ~/ videoDuration.inSeconds * 100,
/// ));
///
/// // Mark as complete when finished
/// await updateProgress(progress.copyWith(
///   isCompleted: true,
///   progressPercent: 100,
///   completedAt: DateTime.now(),
/// ));
/// ```
///
/// ## See Also
///
/// - [TrainingModule] for the module being tracked
/// - [ActivationStatus] for overall training completion
class TrainingProgress {
  /// Unique identifier for this progress record.
  ///
  /// UUID generated by the database.
  final String id;

  /// Reference to the doer whose progress this tracks.
  ///
  /// Foreign key to `doers.id`.
  final String doerId;

  /// Reference to the training module.
  ///
  /// Foreign key to `training_modules.id`.
  final String moduleId;

  /// Whether the module has been completed.
  ///
  /// Set to `true` when the doer finishes viewing the content.
  final bool isCompleted;

  /// Percentage of the module completed (0-100).
  ///
  /// Updated as the doer progresses through the content.
  /// For videos: based on watch time.
  /// For PDFs: based on pages viewed.
  /// For articles: based on scroll position.
  final int progressPercent;

  /// Timestamp when the module was completed.
  ///
  /// `null` if not yet completed.
  final DateTime? completedAt;

  /// Timestamp when the doer first started this module.
  ///
  /// Set when the progress record is created.
  final DateTime startedAt;

  /// Creates a new [TrainingProgress] with the specified values.
  ///
  /// Required parameters:
  /// - [id]: Unique progress identifier
  /// - [doerId]: Reference to the doer
  /// - [moduleId]: Reference to the module
  /// - [startedAt]: When the module was started
  const TrainingProgress({
    required this.id,
    required this.doerId,
    required this.moduleId,
    this.isCompleted = false,
    this.progressPercent = 0,
    this.completedAt,
    required this.startedAt,
  });

  /// Creates a [TrainingProgress] from a JSON map (database response).
  ///
  /// @param json The JSON map from the database response.
  /// @returns A new [TrainingProgress] instance.
  factory TrainingProgress.fromJson(Map<String, dynamic> json) {
    return TrainingProgress(
      id: json['id'] as String,
      doerId: json['doer_id'] as String,
      moduleId: json['module_id'] as String,
      isCompleted: json['is_completed'] as bool? ?? false,
      progressPercent: json['progress_percent'] as int? ?? 0,
      completedAt: json['completed_at'] != null
          ? DateTime.parse(json['completed_at'] as String)
          : null,
      startedAt: DateTime.parse(json['started_at'] as String),
    );
  }

  /// Converts this [TrainingProgress] to a JSON map.
  ///
  /// @returns A map of column names to values.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'doer_id': doerId,
      'module_id': moduleId,
      'is_completed': isCompleted,
      'progress_percent': progressPercent,
      'completed_at': completedAt?.toIso8601String(),
      'started_at': startedAt.toIso8601String(),
    };
  }

  /// Creates a copy of this [TrainingProgress] with updated fields.
  ///
  /// All parameters are optional. Omitted parameters retain their
  /// original values.
  ///
  /// @returns A new [TrainingProgress] instance with the specified changes.
  ///
  /// ## Example
  ///
  /// ```dart
  /// // Update progress percentage
  /// final updated = progress.copyWith(progressPercent: 75);
  ///
  /// // Mark as complete
  /// final completed = progress.copyWith(
  ///   isCompleted: true,
  ///   progressPercent: 100,
  ///   completedAt: DateTime.now(),
  /// );
  /// ```
  TrainingProgress copyWith({
    String? id,
    String? doerId,
    String? moduleId,
    bool? isCompleted,
    int? progressPercent,
    DateTime? completedAt,
    DateTime? startedAt,
  }) {
    return TrainingProgress(
      id: id ?? this.id,
      doerId: doerId ?? this.doerId,
      moduleId: moduleId ?? this.moduleId,
      isCompleted: isCompleted ?? this.isCompleted,
      progressPercent: progressPercent ?? this.progressPercent,
      completedAt: completedAt ?? this.completedAt,
      startedAt: startedAt ?? this.startedAt,
    );
  }
}
