/// Request model and related enums for the supervisor dashboard.
///
/// This file contains:
/// - [RequestModel]: The main data model for client project requests
/// - [ProjectStatus]: Enum representing all possible project statuses
/// - [subjectOptions]: List of available subject/field options
///
/// The models map to the `projects` table in Supabase and handle
/// serialization/deserialization of project data with joined relations.
library;

/// A data model representing a client project request in the supervisor dashboard.
///
/// This model encapsulates all information about a project that needs attention
/// from a supervisor, including client details, deadlines, pricing, and assignment
/// information. It maps to the `projects` table in Supabase with joined data from
/// `profiles`, `subjects`, and `doers` tables.
///
/// ## Usage
///
/// ```dart
/// final request = RequestModel.fromJson(supabaseResponse);
/// print(request.formattedDeadline); // "2d 5h"
/// print(request.isUrgent); // true if deadline < 24 hours
/// ```
///
/// ## Database Mapping
///
/// The model expects joined data in the following format:
/// - `user`: from `profiles` table via `user_id`
/// - `subject`: from `subjects` table via `subject_id`
/// - `doer`: from `doers` table via `doer_id` with nested profile
///
/// See also:
/// - [ProjectStatus] for the status enum
/// - [QuoteModel] for pricing information
/// - [DoerModel] for assigned doer details
class RequestModel {
  /// Creates a new [RequestModel] instance.
  ///
  /// All required fields must be provided. Optional fields default to null
  /// or their specified default values.
  const RequestModel({
    required this.id,
    required this.projectNumber,
    required this.title,
    required this.description,
    required this.clientName,
    required this.subject,
    required this.deadline,
    required this.status,
    required this.createdAt,
    this.userQuote,
    this.doerPayout,
    this.supervisorCommission,
    this.doerId,
    this.doerName,
    this.wordCount,
    this.pageCount,
    this.isPaid = false,
    this.userId,
    this.serviceType,
    this.topic,
    this.specificInstructions,
  });

  /// Unique identifier for the project.
  ///
  /// This is the primary key from the `projects` table (UUID format).
  final String id;

  /// Human-readable project number (e.g., "AX-00001").
  ///
  /// This is auto-generated by the database and used for display
  /// and reference purposes.
  final String projectNumber;

  /// The title or name of the project.
  ///
  /// This is a brief summary provided by the client describing
  /// what they need.
  final String title;

  /// Detailed description of the project requirements.
  ///
  /// Contains the full project brief and specifications
  /// as provided by the client.
  final String description;

  /// The client's display name.
  ///
  /// Retrieved from `profiles.full_name` via the `user_id` foreign key.
  final String clientName;

  /// The subject or field of study for this project.
  ///
  /// Retrieved from `subjects.name` via the `subject_id` foreign key.
  final String subject;

  /// The deadline for project completion.
  ///
  /// This is the date/time by which the project must be delivered
  /// to the client.
  final DateTime deadline;

  /// The current status of the project.
  ///
  /// See [ProjectStatus] for all possible status values and their meanings.
  final ProjectStatus status;

  /// When the project was created/submitted.
  ///
  /// This timestamp is set when the client first submits the project request.
  final DateTime createdAt;

  /// The amount quoted to the user/client in USD.
  ///
  /// This is set when a supervisor creates a quote for the project.
  /// Returns null if the project hasn't been quoted yet.
  final double? userQuote;

  /// The amount to be paid to the assigned doer in USD.
  ///
  /// This is the doer's portion of the project payment.
  /// Returns null if not yet determined.
  final double? doerPayout;

  /// The supervisor's commission for this project in USD.
  ///
  /// This is calculated as a percentage of the total quote.
  /// Returns null if not yet determined.
  final double? supervisorCommission;

  /// The ID of the assigned doer.
  ///
  /// References `doers.id`. Returns null if no doer has been assigned yet.
  final String? doerId;

  /// The name of the assigned doer.
  ///
  /// Retrieved from `profiles.full_name` via `doers.profile_id`.
  /// Returns null if no doer has been assigned yet.
  final String? doerName;

  /// The required word count for the project.
  ///
  /// This is optional and may be specified by the client for
  /// writing-based projects.
  final int? wordCount;

  /// The required page count for the project.
  ///
  /// This is optional and may be specified by the client as
  /// an alternative to word count.
  final int? pageCount;

  /// Whether the client has paid for this project.
  ///
  /// Defaults to false. Set to true when payment is confirmed.
  final bool isPaid;

  /// The client's user ID.
  ///
  /// References `profiles.id` for the user who submitted this request.
  final String? userId;

  /// The type of service requested.
  ///
  /// Examples: "new_project", "proofreading", "editing", etc.
  final String? serviceType;

  /// The topic or subject matter of the project.
  ///
  /// More specific than [subject], this describes the actual
  /// topic the project covers.
  final String? topic;

  /// Any specific instructions from the client.
  ///
  /// Additional requirements or notes that don't fit in the
  /// main description.
  final String? specificInstructions;

  /// Calculates the time remaining until the deadline.
  ///
  /// Returns a [Duration] representing the difference between
  /// the deadline and the current time. A negative duration
  /// indicates the deadline has passed.
  Duration get timeUntilDeadline => deadline.difference(DateTime.now());

  /// Indicates whether the deadline is approaching urgently.
  ///
  /// Returns `true` if the deadline is within 24 hours and hasn't
  /// passed yet. Use this to highlight urgent requests in the UI.
  bool get isUrgent => timeUntilDeadline.inHours < 24 && timeUntilDeadline.isNegative == false;

  /// Indicates whether the deadline has passed.
  ///
  /// Returns `true` if the current time is past the deadline.
  /// These requests should be prioritized or escalated.
  bool get isOverdue => timeUntilDeadline.isNegative;

  /// Returns a human-readable string representation of time until deadline.
  ///
  /// Format varies based on time remaining:
  /// - "Overdue" if deadline has passed
  /// - "Xd Yh" for days and hours
  /// - "Xh Ym" for hours and minutes
  /// - "Xm" for minutes only
  ///
  /// Example outputs: "2d 5h", "3h 45m", "30m", "Overdue"
  String get formattedDeadline {
    final now = DateTime.now();
    final diff = deadline.difference(now);

    if (diff.isNegative) {
      return 'Overdue';
    } else if (diff.inDays > 0) {
      return '${diff.inDays}d ${diff.inHours % 24}h';
    } else if (diff.inHours > 0) {
      return '${diff.inHours}h ${diff.inMinutes % 60}m';
    } else {
      return '${diff.inMinutes}m';
    }
  }

  /// Creates a copy of this [RequestModel] with the specified fields replaced.
  ///
  /// All parameters are optional. If not provided, the current value is retained.
  ///
  /// Returns a new [RequestModel] instance with the updated values.
  RequestModel copyWith({
    String? id,
    String? projectNumber,
    String? title,
    String? description,
    String? clientName,
    String? subject,
    DateTime? deadline,
    ProjectStatus? status,
    DateTime? createdAt,
    double? userQuote,
    double? doerPayout,
    double? supervisorCommission,
    String? doerId,
    String? doerName,
    int? wordCount,
    int? pageCount,
    bool? isPaid,
    String? userId,
    String? serviceType,
    String? topic,
    String? specificInstructions,
  }) {
    return RequestModel(
      id: id ?? this.id,
      projectNumber: projectNumber ?? this.projectNumber,
      title: title ?? this.title,
      description: description ?? this.description,
      clientName: clientName ?? this.clientName,
      subject: subject ?? this.subject,
      deadline: deadline ?? this.deadline,
      status: status ?? this.status,
      createdAt: createdAt ?? this.createdAt,
      userQuote: userQuote ?? this.userQuote,
      doerPayout: doerPayout ?? this.doerPayout,
      supervisorCommission: supervisorCommission ?? this.supervisorCommission,
      doerId: doerId ?? this.doerId,
      doerName: doerName ?? this.doerName,
      wordCount: wordCount ?? this.wordCount,
      pageCount: pageCount ?? this.pageCount,
      isPaid: isPaid ?? this.isPaid,
      userId: userId ?? this.userId,
      serviceType: serviceType ?? this.serviceType,
      topic: topic ?? this.topic,
      specificInstructions: specificInstructions ?? this.specificInstructions,
    );
  }

  /// Creates a [RequestModel] from Supabase projects table JSON response.
  ///
  /// Expects joined data with the following structure:
  /// - `user`: Object with `full_name` from profiles table
  /// - `subject`: Object with `name` from subjects table, or a string
  /// - `doer`: Object with nested `profile` containing `full_name`
  ///
  /// Example query that produces compatible JSON:
  /// ```sql
  /// SELECT *,
  ///   user:profiles!user_id(id, full_name, email),
  ///   subject:subjects!subject_id(id, name),
  ///   doer:doers!doer_id(id, profile:profiles!profile_id(full_name))
  /// FROM projects
  /// ```
  ///
  /// Throws [FormatException] if required fields are missing or malformed.
  factory RequestModel.fromJson(Map<String, dynamic> json) {
    // Extract client name from joined profiles table
    String clientName = 'Unknown Client';
    if (json['user'] is Map) {
      clientName = json['user']['full_name'] as String? ?? 'Unknown Client';
    }

    // Extract subject name from joined subjects table
    String subjectName = 'General';
    if (json['subject'] is Map) {
      subjectName = json['subject']['name'] as String? ?? 'General';
    } else if (json['subject'] is String) {
      subjectName = json['subject'] as String;
    }

    // Extract doer name from joined doers -> profiles
    String? doerName;
    if (json['doer'] is Map && json['doer']['profile'] is Map) {
      doerName = json['doer']['profile']['full_name'] as String?;
    }

    return RequestModel(
      id: json['id'] as String,
      projectNumber: json['project_number'] as String? ?? '',
      title: json['title'] as String,
      description: json['description'] as String? ?? '',
      clientName: clientName,
      subject: subjectName,
      deadline: DateTime.parse(json['deadline'] as String),
      status: ProjectStatus.fromString(json['status'] as String?),
      createdAt: DateTime.parse(json['created_at'] as String),
      userQuote: (json['user_quote'] as num?)?.toDouble(),
      doerPayout: (json['doer_payout'] as num?)?.toDouble(),
      supervisorCommission: (json['supervisor_commission'] as num?)?.toDouble(),
      doerId: json['doer_id'] as String?,
      doerName: doerName,
      wordCount: json['word_count'] as int?,
      pageCount: json['page_count'] as int?,
      isPaid: json['is_paid'] as bool? ?? false,
      userId: json['user_id'] as String?,
      serviceType: json['service_type'] as String?,
      topic: json['topic'] as String?,
      specificInstructions: json['specific_instructions'] as String?,
    );
  }

  /// Converts this [RequestModel] to a JSON map for Supabase operations.
  ///
  /// Returns a [Map] suitable for INSERT or UPDATE operations on the
  /// `projects` table. Note that joined fields (clientName, subject, doerName)
  /// are not included as they are read-only computed fields.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'project_number': projectNumber,
      'title': title,
      'description': description,
      'deadline': deadline.toIso8601String(),
      'status': status.value,
      'created_at': createdAt.toIso8601String(),
      'user_quote': userQuote,
      'doer_payout': doerPayout,
      'supervisor_commission': supervisorCommission,
      'doer_id': doerId,
      'word_count': wordCount,
      'page_count': pageCount,
      'is_paid': isPaid,
      'user_id': userId,
      'service_type': serviceType,
      'topic': topic,
      'specific_instructions': specificInstructions,
    };
  }
}

/// Enumeration of all possible project statuses.
///
/// This enum matches the `project_status` type defined in Supabase
/// and represents the complete lifecycle of a project from submission
/// to completion.
///
/// ## Status Flow
///
/// Typical flow for a successful project:
/// 1. [submitted] - Client submits request
/// 2. [analyzing] - Supervisor reviews request
/// 3. [quoted] - Supervisor provides quote
/// 4. [paymentPending] - Awaiting client payment
/// 5. [paid] - Payment confirmed
/// 6. [assigned] - Doer assigned to project
/// 7. [inProgress] - Doer working on project
/// 8. [submittedForQc] - Doer submits for review
/// 9. [qcApproved] - Quality check passed
/// 10. [delivered] - Sent to client
/// 11. [completed] - Client accepts or auto-approved
///
/// See also:
/// - [RequestModel.status] for usage in request model
/// - [displayName] for UI-friendly status labels
enum ProjectStatus {
  /// Project is in draft state, not yet submitted.
  draft('draft'),

  /// Project has been submitted by client, awaiting supervisor review.
  submitted('submitted'),

  /// Supervisor is analyzing/reviewing the project requirements.
  analyzing('analyzing'),

  /// Supervisor has provided a quote, awaiting client acceptance.
  quoted('quoted'),

  /// Quote accepted, awaiting payment from client.
  paymentPending('payment_pending'),

  /// Payment received, project ready for doer assignment.
  paid('paid'),

  /// Supervisor is in process of assigning a doer.
  assigning('assigning'),

  /// Doer has been assigned to the project.
  assigned('assigned'),

  /// Doer is actively working on the project.
  inProgress('in_progress'),

  /// Doer has submitted work for quality check.
  submittedForQc('submitted_for_qc'),

  /// Quality check is in progress.
  qcInProgress('qc_in_progress'),

  /// Quality check passed, ready for delivery.
  qcApproved('qc_approved'),

  /// Quality check failed, needs revision.
  qcRejected('qc_rejected'),

  /// Project has been delivered to client.
  delivered('delivered'),

  /// Client has requested revisions.
  revisionRequested('revision_requested'),

  /// Doer is working on requested revisions.
  inRevision('in_revision'),

  /// Project completed and accepted by client.
  completed('completed'),

  /// Project auto-approved after delivery period.
  autoApproved('auto_approved'),

  /// Project was cancelled.
  cancelled('cancelled'),

  /// Project was refunded to client.
  refunded('refunded');

  /// Creates a [ProjectStatus] with the specified database value.
  const ProjectStatus(this.value);

  /// The database string value for this status.
  ///
  /// This value is used for storage in the Supabase `project_status` column.
  final String value;

  /// Parses a database string value to a [ProjectStatus].
  ///
  /// Returns [ProjectStatus.submitted] as the default if the value
  /// is null or doesn't match any known status.
  ///
  /// Example:
  /// ```dart
  /// final status = ProjectStatus.fromString('in_progress');
  /// print(status); // ProjectStatus.inProgress
  /// ```
  static ProjectStatus fromString(String? value) {
    return ProjectStatus.values.firstWhere(
      (e) => e.value == value,
      orElse: () => ProjectStatus.submitted,
    );
  }

  /// Returns a human-readable display name for this status.
  ///
  /// Use this for displaying status in the UI. The display name
  /// is more user-friendly than the database value.
  ///
  /// Example:
  /// ```dart
  /// print(ProjectStatus.inProgress.displayName); // "In Progress"
  /// ```
  String get displayName {
    switch (this) {
      case ProjectStatus.draft:
        return 'Draft';
      case ProjectStatus.submitted:
        return 'New Request';
      case ProjectStatus.analyzing:
        return 'Analyzing';
      case ProjectStatus.quoted:
        return 'Quoted';
      case ProjectStatus.paymentPending:
        return 'Payment Pending';
      case ProjectStatus.paid:
        return 'Paid';
      case ProjectStatus.assigning:
        return 'Assigning';
      case ProjectStatus.assigned:
        return 'Assigned';
      case ProjectStatus.inProgress:
        return 'In Progress';
      case ProjectStatus.submittedForQc:
        return 'For Review';
      case ProjectStatus.qcInProgress:
        return 'QC In Progress';
      case ProjectStatus.qcApproved:
        return 'QC Approved';
      case ProjectStatus.qcRejected:
        return 'QC Rejected';
      case ProjectStatus.delivered:
        return 'Delivered';
      case ProjectStatus.revisionRequested:
        return 'Revision Requested';
      case ProjectStatus.inRevision:
        return 'In Revision';
      case ProjectStatus.completed:
        return 'Completed';
      case ProjectStatus.autoApproved:
        return 'Auto Approved';
      case ProjectStatus.cancelled:
        return 'Cancelled';
      case ProjectStatus.refunded:
        return 'Refunded';
    }
  }

  /// Indicates whether this status represents a new/pending request.
  ///
  /// Returns `true` only for [submitted] status.
  bool get isNewRequest => this == ProjectStatus.submitted;

  /// Indicates whether payment has been made for this project.
  ///
  /// Returns `true` for all statuses after [paid], excluding
  /// [cancelled] and [refunded].
  bool get isPaidStatus => index >= ProjectStatus.paid.index && this != ProjectStatus.cancelled && this != ProjectStatus.refunded;

  /// Indicates whether the project is currently being worked on.
  ///
  /// Returns `true` for statuses where a doer is actively working
  /// or the project is in review: [assigned], [inProgress],
  /// [submittedForQc], [qcInProgress], and [inRevision].
  bool get isActive => [
        ProjectStatus.assigned,
        ProjectStatus.inProgress,
        ProjectStatus.submittedForQc,
        ProjectStatus.qcInProgress,
        ProjectStatus.inRevision,
      ].contains(this);

  /// Indicates whether this project requires supervisor action.
  ///
  /// Returns `true` for statuses where the supervisor needs to
  /// take action: [submitted], [paid], [submittedForQc], and
  /// [revisionRequested].
  bool get needsAction => [
        ProjectStatus.submitted,
        ProjectStatus.paid,
        ProjectStatus.submittedForQc,
        ProjectStatus.revisionRequested,
      ].contains(this);
}

/// List of available subject/field options for filtering.
///
/// This list is used in UI dropdowns and filters to allow users
/// to filter projects by subject area. The first option "All"
/// represents no filter (show all subjects).
///
/// These values should match the subjects available in the
/// `subjects` table in Supabase.
const List<String> subjectOptions = [
  'All',
  'Academic Writing',
  'Business Studies',
  'Computer Science',
  'Data Analysis',
  'Economics',
  'Engineering',
  'Finance',
  'Healthcare',
  'Law',
  'Marketing',
  'Mathematics',
  'Programming',
  'Research',
  'Statistics',
  'Technical Writing',
];
