#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for User App Feature Completion
# Spec: 001-user-app-completion

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start on port $port${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready on port $port${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check if Node.js is installed
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed. Please install Node.js 18+${NC}"
    exit 1
fi

# Check if npm is installed
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed. Please install npm${NC}"
    exit 1
fi

# Check if Flutter is installed (optional for this spec)
if command -v flutter &> /dev/null; then
    echo -e "${GREEN}Flutter found${NC}"
else
    echo -e "${YELLOW}Flutter not found - skipping user_app${NC}"
fi

echo -e "${GREEN}Prerequisites check passed${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."

# user-web dependencies
if [ -d "user-web" ]; then
    echo "Installing user-web dependencies..."
    cd user-web
    npm install
    cd ..
    echo -e "${GREEN}user-web dependencies installed${NC}"
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting services..."

# Start user-web
if [ -d "user-web" ]; then
    echo "Starting user-web..."
    cd user-web
    npm run dev &
    USER_WEB_PID=$!
    cd ..
    wait_for_service 3000 "user-web"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  user-web: http://localhost:3000"
echo ""
echo "Key Pages to Test:"
echo "  Home:            http://localhost:3000/home"
echo "  Connect:         http://localhost:3000/connect"
echo "  Payment Methods: http://localhost:3000/payment-methods"
echo "  Wallet:          http://localhost:3000/wallet"
echo ""
echo "To stop services, press Ctrl+C"
echo ""

# Keep script running
wait
